/* eslint-disable */
// This file is generated by webapp/scripts/generate-legal-content.mjs from webapp/messages/en/legal.md.
// Do not edit this file directly.

export type LegalBlock = {
  type: "paragraph"
  text: string
}

export type LegalSection = {
  title: string
  blocks: LegalBlock[]
}

export const LEGAL_CONTENT_SECTIONS = [
  {
    "title": "legal notice",
    "blocks": [
      {
        "type": "paragraph",
        "text": "information according to section 5 ddg."
      }
    ]
  },
  {
    "title": "provider",
    "blocks": [
      {
        "type": "paragraph",
        "text": "**ingo wörner**\nnaststr. 1\n70376 stuttgart\ngermany"
      }
    ]
  },
  {
    "title": "contact",
    "blocks": [
      {
        "type": "paragraph",
        "text": "[hello@swiss-grid-generator.com](mailto:hello@swiss-grid-generator.com)"
      }
    ]
  },
  {
    "title": "responsible for own content",
    "blocks": [
      {
        "type": "paragraph",
        "text": "ingo wörner\nnaststr. 1\n70376 stuttgart\ngermany"
      }
    ]
  },
  {
    "title": "privacy",
    "blocks": [
      {
        "type": "paragraph",
        "text": "the controller for personal data processed by swiss grid generator is ingo wörner, contactable at the email address above."
      },
      {
        "type": "paragraph",
        "text": "the app processes account email addresses, authentication data, cloud project data, feedback messages, attached screenshots, optional support logs, and technical data required to operate the service."
      },
      {
        "type": "paragraph",
        "text": "processing is used to provide the editor, sign-in, cloud storage, feedback, support, security, and synchronization features. legal bases are contract performance, legitimate interests, and consent where required."
      }
    ]
  },
  {
    "title": "cloud storage",
    "blocks": [
      {
        "type": "paragraph",
        "text": "signed-in users can store projects in supabase. user projects and uploaded project content remain the responsibility of the respective user."
      }
    ]
  },
  {
    "title": "local storage",
    "blocks": [
      {
        "type": "paragraph",
        "text": "the app uses local storage and indexeddb for editor preferences, offline cache, recent local activity logs, and project synchronization. these are required for the requested editor and cloud-sync features. the app does not use advertising or analytics cookies."
      }
    ]
  },
  {
    "title": "feedback",
    "blocks": [
      {
        "type": "paragraph",
        "text": "feedback submissions are stored in supabase and may include email, comment, screenshots, app version, and optional local support logs. they are used only to handle support, bug reports, and product feedback."
      }
    ]
  },
  {
    "title": "user rights",
    "blocks": [
      {
        "type": "paragraph",
        "text": "users may request access, correction, deletion, restriction, portability, or objection by email. users may also lodge a complaint with a competent data protection supervisory authority."
      }
    ]
  },
  {
    "title": "terms of use",
    "blocks": [
      {
        "type": "paragraph",
        "text": "swiss grid generator is provided as a professional design tool without a guarantee of uninterrupted availability. users are responsible for their own documents, exports, backups, and lawful use of uploaded or stored content."
      }
    ]
  },
  {
    "title": "consumer dispute resolution",
    "blocks": [
      {
        "type": "paragraph",
        "text": "we are not willing or obliged to participate in dispute resolution proceedings before a consumer arbitration board."
      }
    ]
  },
  {
    "title": "note",
    "blocks": [
      {
        "type": "paragraph",
        "text": "this compact legal notice is provided in english because the app interface is english only."
      }
    ]
  }
] as const satisfies readonly LegalSection[]
