/* eslint-disable */
// This file is generated by webapp/scripts/generate-tooltip-content.mjs from webapp/messages/en/tooltips.md.
// Do not edit this file directly.

export type TooltipBlock =
  | { type: "paragraph"; text: string }
  | { type: "list"; items: string[] }

export type LayoutOpenTooltipItem = {
  id: string
  title: string
  blocks: TooltipBlock[]
}

export const LAYOUT_OPEN_TOOLTIP_ITEMS = [
  {
    "id": "tooltip-start-with-system",
    "title": "Start With The Page System",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Set ratio, baseline, margins, grid, rhythm, and type."
      },
      {
        "type": "paragraph",
        "text": "Correct the system before correcting paragraphs."
      }
    ]
  },
  {
    "id": "tooltip-structure-before-styling",
    "title": "Structure Before Styling",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Define the frame with `Rows`, `Baselines`, and `Cols`. The frame is the editorial decision."
      }
    ]
  },
  {
    "id": "tooltip-repetitive-reference",
    "title": "Use Repetitive As A Control",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Start with `Repetitive` rhythm. Judge margins, baseline, and hierarchy before adding asymmetry."
      }
    ]
  },
  {
    "id": "tooltip-create-text",
    "title": "Create Text On The Grid",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Double-click a module. The block starts at that structural point and clamps to the column field."
      }
    ]
  },
  {
    "id": "tooltip-create-hierarchy",
    "title": "Choose Hierarchy While Creating",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Hold `1..5` while double-clicking: `1 Caption`, `2 Body`, `3 Subhead`, `4 Headline`, `5 Display`."
      }
    ]
  },
  {
    "id": "tooltip-create-image",
    "title": "Place Image Placeholders Deliberately",
    "blocks": [
      {
        "type": "paragraph",
        "text": "`Shift` + double-click creates an image placeholder on the same grid discipline as text."
      }
    ]
  },
  {
    "id": "tooltip-lorem-frame-test",
    "title": "Use Lorem As A Frame Test",
    "blocks": [
      {
        "type": "paragraph",
        "text": "`<%lorem%>` tests measure, density, line count, reflow, and hyphenation."
      }
    ]
  },
  {
    "id": "tooltip-drag-and-nudge",
    "title": "Drag For Placement, Nudge For Decision",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Drag for position. Use cursor keys for measured correction."
      }
    ]
  },
  {
    "id": "tooltip-cursor-nudge",
    "title": "Nudge With The Grid",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Snap moves by columns and module rows. `Shift` moves snapped Y by baseline rows."
      }
    ]
  },
  {
    "id": "tooltip-duplicate-layer",
    "title": "Duplicate Without Losing Rhythm",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use `+`. `Shift` copies paragraph geometry. `Alt/Option` copies type. Both copy both."
      }
    ]
  },
  {
    "id": "tooltip-free-placement",
    "title": "Free Placement Is An Exception",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Turn snap off only for controlled optical tension."
      }
    ]
  },
  {
    "id": "tooltip-smart-text-zoom",
    "title": "Paragraph Zoom Keeps The Work Local",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Keep paragraph zoom on for text work. Geometry changes refit the view."
      }
    ]
  },
  {
    "id": "tooltip-turbo-edit",
    "title": "Retarget Paragraph To Paragraph",
    "blocks": [
      {
        "type": "paragraph",
        "text": "With an editor open, select another unlocked paragraph to retarget."
      }
    ]
  },
  {
    "id": "tooltip-layer-card-retarget",
    "title": "Retarget From Layer Cards",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Double-click an unlocked layer card to open or retarget. Single-click selects for nudging."
      }
    ]
  },
  {
    "id": "tooltip-rendered-text-editing",
    "title": "Edit The Rendered Text",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Inline editing follows rendered lines. Double-click word. Triple-click sentence."
      }
    ]
  },
  {
    "id": "tooltip-placeholder-editing",
    "title": "Keep Tokens Visible While Editing",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Variables remain raw while editing and render live outside edit mode."
      }
    ]
  },
  {
    "id": "tooltip-rows-plus-baselines",
    "title": "Height Is Rows Plus Baselines",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Height is `Rows + Baselines`. Use baseline-only frames for captions, folios, proof lines."
      }
    ]
  },
  {
    "id": "tooltip-columns-before-reflow",
    "title": "Set Columns Before Reflow",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Set `Cols` before judging flow. Weak measure is usually a frame problem."
      }
    ]
  },
  {
    "id": "tooltip-frame-alignment",
    "title": "Align Inside The Frame",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Alignment positions text inside the frame. It is composition, not repair."
      }
    ]
  },
  {
    "id": "tooltip-custom-type",
    "title": "Use Custom Type Sparingly",
    "blocks": [
      {
        "type": "paragraph",
        "text": "`Custom` is a local exception after hierarchy is resolved."
      }
    ]
  },
  {
    "id": "tooltip-select-before-nudge",
    "title": "Select Before Nudging",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Select a layer card, then nudge."
      }
    ]
  },
  {
    "id": "tooltip-lock-finished-layers",
    "title": "Lock Resolved Layers",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Lock resolved layers. Locked layers show guides but cannot change."
      }
    ]
  },
  {
    "id": "tooltip-page-cards",
    "title": "Use Page Rows For Document Rhythm",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Page order is part of the design."
      }
    ]
  },
  {
    "id": "tooltip-facing-pages",
    "title": "Use Facing Pages Only For Spreads",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use `Facing pages` for one continuous field across two physical pages."
      }
    ]
  },
  {
    "id": "tooltip-preview-guides",
    "title": "Toggle Guides While Judging",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Inspect baseline, margins, modules, type, and placeholders. Then hide what is not needed."
      }
    ]
  },
  {
    "id": "tooltip-rollover-guides",
    "title": "Rollover Guides Show The Frame",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Hover reveals the configured frame, not only visible text."
      }
    ]
  },
  {
    "id": "tooltip-help-hover",
    "title": "Help Hover Is Contextual",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Open Help and hover marked areas for the matching reference."
      }
    ]
  },
  {
    "id": "tooltip-export-readiness",
    "title": "Export After The System Is Stable",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Confirm order, range, guides, rotation, folios, and variables."
      }
    ]
  },
  {
    "id": "tooltip-export-format",
    "title": "Choose Export By Downstream Use",
    "blocks": [
      {
        "type": "paragraph",
        "text": "JSON edits. PDF outputs. SVG freezes pages. IDML continues in InDesign."
      }
    ]
  },
  {
    "id": "tooltip-export-bleed",
    "title": "Shared Vector Bleed",
    "blocks": [
      {
        "type": "paragraph",
        "text": "One bleed control serves PDF, SVG, and IDML."
      }
    ]
  },
  {
    "id": "tooltip-export-visibility",
    "title": "Visible Overlays Are Exported",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Export follows current guide visibility."
      }
    ]
  },
  {
    "id": "tooltip-export-progress",
    "title": "Export Progress",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Progress is informational. Export continues from the committed page plan."
      }
    ]
  },
  {
    "id": "tooltip-fix-loose-page",
    "title": "If The Page Feels Loose",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Return to baseline, margins, and grid rhythm."
      }
    ]
  },
  {
    "id": "tooltip-fix-weak-type",
    "title": "If Text Feels Weak",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Check hierarchy, measure, leading, and baseline before tracking."
      }
    ]
  },
  {
    "id": "tooltip-grid-reduction",
    "title": "If Content Falls Out Of Bounds",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Resolve placement before reducing rows or columns."
      }
    ]
  },
  {
    "id": "tooltip-faster-editing",
    "title": "If Editing Feels Slow",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Keep one editor open and retarget in context."
      }
    ]
  }
] as const satisfies readonly LayoutOpenTooltipItem[]
