/* eslint-disable */
// This file is generated by webapp/scripts/generate-help-content.mjs from webapp/messages/en/content/help.md.
// Do not edit this file directly.

export type HelpDirectiveName = "APP_VERSION" | "AVAILABLE_FONTS" | "SHORTCUT_TABLE" | "DOCUMENT_VARIABLE_TOKENS"

export type HelpBlock =
  | { type: "paragraph"; text: string }
  | { type: "list"; items: string[] }
  | { type: "directive"; name: HelpDirectiveName }

export type HelpSubsection = {
  id: string
  title: string
  indexed: boolean
  blocks: HelpBlock[]
}

export type HelpSection = {
  id: string
  title: string
  indexed: boolean
  blocks: HelpBlock[]
  subsections: HelpSubsection[]
}

export type HelpGroup = {
  title: string
  sections: HelpSection[]
}

export const HELP_CONTENT_GROUPS = [
  {
    "title": "Quick Start",
    "sections": [
      {
        "title": "Quick Start",
        "id": "help-quick-start",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Set `Canvas`: ratio, orientation, rotation.",
              "Set `Baseline`: vertical rhythm.",
              "Set `Margins`: page frame.",
              "Set `Grid`: columns, rows, gutters, rhythm.",
              "Set `Typography`: hierarchy and base family.",
              "Use header toggles to inspect structure."
            ]
          }
        ],
        "subsections": []
      }
    ]
  },
  {
    "title": "General Guidance",
    "sections": [
      {
        "title": "Settings Reference",
        "id": "help-settings-overview",
        "indexed": false,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Core page system controls."
          }
        ],
        "subsections": []
      },
      {
        "title": "Canvas",
        "id": "help-canvas-ratio",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Ratio defines page proportion.",
              "Orientation swaps axes.",
              "Rotation turns the preview and export page.",
              "Custom ratio preserves A4-equivalent area."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Baseline",
        "id": "help-baseline-grid",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Baseline sets vertical rhythm.",
              "Grid unit controls margins, modules, and leading.",
              "Larger units reduce available lines."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Margins",
        "id": "help-margins",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Margin method defines page frame.",
              "Progressive, Van de Graaf, and Baseline are canon presets.",
              "Custom margins use baseline-unit sides."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Grid",
        "id": "help-gutter",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Columns and rows define the modular field.",
              "Gutter multiple sets module separation.",
              "Rhythm distributes modules by equal, Fibonacci, golden, fourth, or fifth proportion.",
              "Direction controls non-repetitive rhythm flow."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Typography",
        "id": "help-typo",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Base family sets default rendering.",
              "Rhythm sets type scale.",
              "Hierarchy remains the primary structure.",
              "`Custom` is paragraph-local."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Color",
        "id": "help-color-scheme",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Base scheme defines placeholder color families.",
              "Background swatches set page ground per page.",
              "Active swatch click clears the ground."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "General Guidance",
        "id": "help-general-overview",
        "indexed": false,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Core editing and layout workflows."
          }
        ],
        "subsections": []
      },
      {
        "title": "Preview Workspace",
        "id": "help-preview-workspace",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "The preview is the active page surface.",
              "Pages appear after the final page plan is ready.",
              "Double-click an empty module for text. `Shift` + double-click for image.",
              "Hold `1..5` while creating text: `1 Caption`, `2 Body`, `3 Subhead`, `4 Headline`, `5 Display`.",
              "New blocks clamp to the remaining field.",
              "Hover layers for edit access and guides.",
              "Drag to place. Arrow keys refine.",
              "`+` duplicates. `Shift` copies paragraph geometry. `Alt/Option` copies type. Both copy both.",
              "Visibility toggles control preview and export.",
              "Locked layers remain visible but fixed.",
              "Snapped axes move on grid. Unsnapped axes move in fine steps.",
              "`Page Up`, `Page Down`, `Home`, and `End` navigate pages.",
              "Undo and redo cover settings, placement, deletion, and editor changes."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Text Editor",
        "id": "help-editor",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Open from preview or an unlocked text layer card.",
              "Select another unlocked paragraph to retarget.",
              "The sidebar becomes `Paragraph`, `Typography`, `Symbols`, `Placeholders`, `Info`.",
              "Section state is document-local.",
              "`Esc` or outside click exits.",
              "Double-click selects word. Triple-click selects sentence. Four clicks select paragraph.",
              "`Alt+A` or `Cmd/Ctrl+A` selects all."
            ]
          }
        ],
        "subsections": [
          {
            "title": "Paragraph Section",
            "id": "help-editor-paragraph",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Set rows, baselines, columns, alignment, flow, snap, rotation.",
                  "Frame height is `Rows + Baselines`.",
                  "`Rows` may be `0` when `Baselines` is greater than `0`.",
                  "`Rows`, `Baselines`, and `Cols` preview on rollover.",
                  "`Snap to Columns (X)` locks column anchors.",
                  "`Snap to Baseline (Y)` locks baseline rhythm."
                ]
              }
            ]
          },
          {
            "title": "Typography Section",
            "id": "help-editor-typo",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Set hierarchy, family, cut, color, kerning, tracking, custom size, leading.",
                  "`Custom` starts from resolved paragraph metrics.",
                  "Selection receives type and color changes.",
                  "Family, cut, hierarchy, kerning, and scheme preview on rollover."
                ]
              }
            ]
          },
          {
            "title": "Symbols Section",
            "id": "help-editor-symbols",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Insert symbols at caret or selection.",
                  "Groups: arrows, bullets, marks, math, Greek, geometry, editorial.",
                  "Symbols export through `Noto Sans Symbols 2`.",
                  "Recent symbols appear after first use."
                ]
              }
            ]
          },
          {
            "title": "Placeholders Section",
            "id": "help-editor-placeholders",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Insert document-variable tokens.",
                  "`<%lorem%>` fills the active frame.",
                  "`<%page%>` and `<%pages%>` use physical page counts.",
                  "Available tokens: {{DOCUMENT_VARIABLE_TOKENS}}."
                ]
              }
            ]
          },
          {
            "title": "Info Section",
            "id": "help-editor-info",
            "indexed": true,
            "blocks": [
              {
                "type": "paragraph",
                "text": "Geometry, type summary, counts, line capacity."
              }
            ]
          }
        ]
      },
      {
        "title": "Image Editor",
        "id": "help-image-editor",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "`Shift` + double-click an empty module creates an image placeholder.",
              "Open from preview or an unlocked image layer card.",
              "The sidebar becomes `Geometry`, `Color`, `Info`.",
              "Section state is document-local.",
              "`Esc` or outside click exits.",
              "Double-click another unlocked image card to retarget."
            ]
          }
        ],
        "subsections": [
          {
            "title": "Geometry Section",
            "id": "help-image-editor-geometry",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Set rows, baselines, columns, snap, rotation.",
                  "Frame height is `Rows + Baselines`.",
                  "`Rows`, `Baselines`, and `Cols` preview on rollover."
                ]
              }
            ]
          },
          {
            "title": "Color Section",
            "id": "help-image-editor-color",
            "indexed": true,
            "blocks": [
              {
                "type": "paragraph",
                "text": "Scheme, swatch, transparency."
              }
            ]
          },
          {
            "title": "Info Section",
            "id": "help-image-editor-info",
            "indexed": true,
            "blocks": [
              {
                "type": "paragraph",
                "text": "Geometry, snap, rotation, scheme, color, transparency."
              }
            ]
          }
        ]
      },
      {
        "title": "Drag and Placement",
        "id": "help-drag-placement",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Drag follows X and Y snap.",
              "Baseline snap uses module tops.",
              "`Shift` drag moves Y by baseline rows.",
              "Unsnapped layers stay within bounds.",
              "Column snap off allows one-column side overhang.",
              "Cursor keys move selected layers. `Shift` increases step."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "History and Reflow",
        "id": "help-history-reflow",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Undo and redo cover settings, content, placement.",
              "Grid reduction never moves layers silently.",
              "Out-of-bounds content blocks reduction."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Save and Load",
        "id": "help-save-load",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Save stores metadata, pages, settings, layers, tours.",
              "`Save to library` stores a compressed local archive.",
              "`Import` restores JSON or `.swissgridgenerator`.",
              "Imported projects require the 2.0 `pages` schema.",
              "Logical anchors keep layouts stable across grid changes.",
              "Supabase auth is only for cloud sync."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Export",
        "id": "help-export",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Formats: JSON, PDF, SVG, IDML.",
              "Multi-page projects export ranges or explicit pages.",
              "Export uses project guide visibility.",
              "PDF, SVG, and IDML are vector exports from the shared page plan.",
              "Text exports as frozen outline geometry.",
              "Workers keep long exports responsive where supported.",
              "SVG and IDML can reuse exact-request page artifacts.",
              "JSON remains editable.",
              "Export metadata does not alter the live project unless JSON is saved.",
              "Metadata is written to PDF, SVG, and IDML where supported.",
              "One bleed control defines trim, bleed, media, origin, crop marks, guides.",
              "PDF uses RGB vector geometry with sRGB output intent.",
              "Multi-page SVG exports a ZIP.",
              "IDML separates guide, typography, and placeholder layers.",
              "`Esc` closes or cancels."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Project Tours",
        "id": "help-project-tours",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Projects may include a guided tour.",
              "Reopen closed tours from `Open tour`.",
              "Steps can change pages, highlight layers, open editors, open help, or wait for a layer click."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Layout Tooltips",
        "id": "help-layout-tooltips",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Presets and projects may open workflow tips.",
              "`Next` advances the sequence.",
              "Help hover connects tips to reference sections."
            ]
          }
        ],
        "subsections": []
      }
    ]
  },
  {
    "title": "Application Controls",
    "sections": [
      {
        "title": "UX Reference",
        "id": "help-ux-overview",
        "indexed": false,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Global controls and panel behavior."
          }
        ],
        "subsections": []
      },
      {
        "title": "Application Controls",
        "id": "help-application-controls-overview",
        "indexed": false,
        "blocks": [],
        "subsections": []
      },
      {
        "title": "Header and Sidebars",
        "id": "help-sidebars-header",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Header: presets, import, save, export, undo, redo, zoom, visibility, Project, account, more.",
              "More: theme, Help, Feedback, Legal.",
              "Project panel: `Cmd/Ctrl+Shift+P`."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Help Navigation",
        "id": "help-help-navigation",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Open Help, then hover marked targets.",
              "Header, settings, editor sections, preview, and presets are covered.",
              "Up-arrow returns to index."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Presets",
        "id": "help-header-examples",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Opens preset browser.",
              "Groups: `Presets`, `Examples`, `Users`.",
              "`Users` appears when saved layouts exist.",
              "The info marker covers local storage, data clearing, cloud sync.",
              "Hover shows metadata.",
              "Green dot means signed in and synced.",
              "Delete confirms, removes locally, then reports cloud state.",
              "Double-click loads.",
              "`Esc` closes.",
              "Shortcut: `Cmd/Ctrl+Shift+4`."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Import",
        "id": "help-header-load",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Imports JSON or `.swissgridgenerator`. Shortcut: `Cmd/Ctrl+O`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Save",
        "id": "help-header-save",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Stores the project in `Users`. Red dot: unsaved. Orange: local. Green: cloud-synced. Shortcut: `Cmd/Ctrl+S`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Cloud Account",
        "id": "help-cloud-account",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Opens cloud account.",
              "Green dot means signed in and synced.",
              "Sign-in uses Supabase email code.",
              "`Cloud state` shows local account and sync events.",
              "`Sync now` runs manual sync.",
              "Saved projects auto-save locally and sync when possible.",
              "Remote deletions apply locally unless local changes are newer.",
              "Conflicts require source selection.",
              "Failures use translated status messages.",
              "Hidden or closed tabs attempt local autosave and cloud sync."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Export",
        "id": "help-header-export",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Opens export. Shortcut: `Cmd/Ctrl+Shift+E`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Undo",
        "id": "help-header-undo",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Reverts one step. Shortcut: `Cmd/Ctrl+Z`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Redo",
        "id": "help-header-redo",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Reapplies one step. Shortcut: `Cmd/Ctrl+Shift+Z` or `Cmd/Ctrl+Y`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Dark Mode",
        "id": "help-header-dark-mode",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Toggles light and dark UI. Shortcut: `Cmd/Ctrl+Shift+D`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Paragraph Zoom",
        "id": "help-header-smart-text-zoom",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Toggles zoom-to-paragraph during text editing."
          }
        ],
        "subsections": []
      },
      {
        "title": "Baselines Toggle",
        "id": "help-header-baselines",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Shows baseline rhythm. Shortcut: `Cmd/Ctrl+Shift+B`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Margins Toggle",
        "id": "help-header-margins",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Shows margin frame. Shortcut: `Cmd/Ctrl+Shift+M`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Modules Toggle",
        "id": "help-header-modules",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Shows modular field and gutters. Shortcut: `Cmd/Ctrl+Shift+G`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Typography Toggle",
        "id": "help-header-typography",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Shows typography overlay. Shortcut: `Cmd/Ctrl+Shift+T`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Image Placeholders Toggle",
        "id": "help-header-image-placeholders",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Shows image placeholders. Shortcut: `Cmd/Ctrl+Shift+J`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Project Panel",
        "id": "help-header-layers",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Metadata, page order, layers.",
              "`i` toggles document data.",
              "Double-click project title to edit metadata.",
              "Page header returns to page list.",
              "Page counter shows physical page position. Double-click jumps.",
              "Click page row to activate. Double-click opens layers.",
              "`Page Up`, `Page Down`, `Home`, `End` navigate.",
              "Drag page rows to reorder.",
              "Rename and delete controls sit in each row.",
              "Last page cannot be deleted.",
              "`Facing pages` creates one spread record.",
              "`+` adds a page. `Shift` + `+` duplicates content.",
              "Maximum: `1000` pages.",
              "Layer cards mirror preview hover.",
              "Drag unlocked layer cards to reorder z-index.",
              "Lock and delete controls sit in each card.",
              "Double-click unlocked card to open or retarget editor."
            ]
          }
        ],
        "subsections": []
      }
    ]
  }
] as const satisfies readonly HelpGroup[]

export const HELP_INDEX_GROUPS = [
  {
    "title": "Quick Start",
    "items": [
      {
        "id": "help-quick-start",
        "label": "Quick Start"
      }
    ]
  },
  {
    "title": "General Guidance",
    "items": [
      {
        "id": "help-canvas-ratio",
        "label": "Canvas"
      },
      {
        "id": "help-baseline-grid",
        "label": "Baseline"
      },
      {
        "id": "help-margins",
        "label": "Margins"
      },
      {
        "id": "help-gutter",
        "label": "Grid"
      },
      {
        "id": "help-typo",
        "label": "Typography"
      },
      {
        "id": "help-color-scheme",
        "label": "Color"
      },
      {
        "id": "help-preview-workspace",
        "label": "Preview Workspace"
      },
      {
        "id": "help-editor",
        "label": "Text Editor"
      },
      {
        "id": "help-image-editor",
        "label": "Image Editor"
      },
      {
        "id": "help-drag-placement",
        "label": "Drag and Placement"
      },
      {
        "id": "help-history-reflow",
        "label": "History and Reflow"
      },
      {
        "id": "help-save-load",
        "label": "Save and Load"
      },
      {
        "id": "help-export",
        "label": "Export"
      },
      {
        "id": "help-project-tours",
        "label": "Project Tours"
      },
      {
        "id": "help-layout-tooltips",
        "label": "Layout Tooltips"
      }
    ]
  },
  {
    "title": "Application Controls",
    "items": [
      {
        "id": "help-sidebars-header",
        "label": "Header and Sidebars"
      },
      {
        "id": "help-help-navigation",
        "label": "Help Navigation"
      },
      {
        "id": "help-header-examples",
        "label": "Presets"
      },
      {
        "id": "help-header-load",
        "label": "Import"
      },
      {
        "id": "help-header-save",
        "label": "Save"
      },
      {
        "id": "help-cloud-account",
        "label": "Cloud Account"
      },
      {
        "id": "help-header-export",
        "label": "Export"
      },
      {
        "id": "help-header-undo",
        "label": "Undo"
      },
      {
        "id": "help-header-redo",
        "label": "Redo"
      },
      {
        "id": "help-header-dark-mode",
        "label": "Dark Mode"
      },
      {
        "id": "help-header-smart-text-zoom",
        "label": "Paragraph Zoom"
      },
      {
        "id": "help-header-baselines",
        "label": "Baselines Toggle"
      },
      {
        "id": "help-header-margins",
        "label": "Margins Toggle"
      },
      {
        "id": "help-header-modules",
        "label": "Modules Toggle"
      },
      {
        "id": "help-header-typography",
        "label": "Typography Toggle"
      },
      {
        "id": "help-header-image-placeholders",
        "label": "Image Placeholders Toggle"
      },
      {
        "id": "help-header-layers",
        "label": "Project Panel"
      }
    ]
  }
] as const

export const ALL_HELP_INDEX_ITEMS = [
  {
    "id": "help-quick-start",
    "label": "Quick Start"
  },
  {
    "id": "help-settings-overview",
    "label": "Settings Reference"
  },
  {
    "id": "help-canvas-ratio",
    "label": "Canvas"
  },
  {
    "id": "help-baseline-grid",
    "label": "Baseline"
  },
  {
    "id": "help-margins",
    "label": "Margins"
  },
  {
    "id": "help-gutter",
    "label": "Grid"
  },
  {
    "id": "help-typo",
    "label": "Typography"
  },
  {
    "id": "help-color-scheme",
    "label": "Color"
  },
  {
    "id": "help-general-overview",
    "label": "General Guidance"
  },
  {
    "id": "help-preview-workspace",
    "label": "Preview Workspace"
  },
  {
    "id": "help-editor",
    "label": "Text Editor"
  },
  {
    "id": "help-image-editor",
    "label": "Image Editor"
  },
  {
    "id": "help-drag-placement",
    "label": "Drag and Placement"
  },
  {
    "id": "help-history-reflow",
    "label": "History and Reflow"
  },
  {
    "id": "help-save-load",
    "label": "Save and Load"
  },
  {
    "id": "help-export",
    "label": "Export"
  },
  {
    "id": "help-project-tours",
    "label": "Project Tours"
  },
  {
    "id": "help-layout-tooltips",
    "label": "Layout Tooltips"
  },
  {
    "id": "help-ux-overview",
    "label": "UX Reference"
  },
  {
    "id": "help-application-controls-overview",
    "label": "Application Controls"
  },
  {
    "id": "help-sidebars-header",
    "label": "Header and Sidebars"
  },
  {
    "id": "help-help-navigation",
    "label": "Help Navigation"
  },
  {
    "id": "help-header-examples",
    "label": "Presets"
  },
  {
    "id": "help-header-load",
    "label": "Import"
  },
  {
    "id": "help-header-save",
    "label": "Save"
  },
  {
    "id": "help-cloud-account",
    "label": "Cloud Account"
  },
  {
    "id": "help-header-export",
    "label": "Export"
  },
  {
    "id": "help-header-undo",
    "label": "Undo"
  },
  {
    "id": "help-header-redo",
    "label": "Redo"
  },
  {
    "id": "help-header-dark-mode",
    "label": "Dark Mode"
  },
  {
    "id": "help-header-smart-text-zoom",
    "label": "Paragraph Zoom"
  },
  {
    "id": "help-header-baselines",
    "label": "Baselines Toggle"
  },
  {
    "id": "help-header-margins",
    "label": "Margins Toggle"
  },
  {
    "id": "help-header-modules",
    "label": "Modules Toggle"
  },
  {
    "id": "help-header-typography",
    "label": "Typography Toggle"
  },
  {
    "id": "help-header-image-placeholders",
    "label": "Image Placeholders Toggle"
  },
  {
    "id": "help-header-layers",
    "label": "Project Panel"
  }
] as const

export const EDITOR_HELP_SUBSECTION_ITEMS = [
  {
    "id": "help-editor-paragraph",
    "label": "Text Editor / Paragraph"
  },
  {
    "id": "help-editor-typo",
    "label": "Text Editor / Typography"
  },
  {
    "id": "help-editor-symbols",
    "label": "Text Editor / Symbols"
  },
  {
    "id": "help-editor-placeholders",
    "label": "Text Editor / Placeholders"
  },
  {
    "id": "help-editor-info",
    "label": "Text Editor / Info"
  },
  {
    "id": "help-image-editor-geometry",
    "label": "Image Editor / Geometry"
  },
  {
    "id": "help-image-editor-color",
    "label": "Image Editor / Color"
  },
  {
    "id": "help-image-editor-info",
    "label": "Image Editor / Info"
  }
] as const

export const ALL_HELP_SECTION_ITEMS = [
  ...ALL_HELP_INDEX_ITEMS,
  ...EDITOR_HELP_SUBSECTION_ITEMS,
] as const

export type HelpSectionId = (typeof ALL_HELP_SECTION_ITEMS)[number]["id"]
