/* eslint-disable */
// This file is generated by webapp/scripts/generate-legal-content.mjs from webapp/messages/en/content/legal.md.
// Do not edit this file directly.

export type LegalBlock = {
  type: "paragraph"
  text: string
}

export type LegalSection = {
  title: string
  blocks: LegalBlock[]
}

export const LEGAL_CONTENT_SECTIONS = [
  {
    "title": "legal notice",
    "blocks": [
      {
        "type": "paragraph",
        "text": "information according to Section 5 DDG."
      }
    ]
  },
  {
    "title": "provider",
    "blocks": [
      {
        "type": "paragraph",
        "text": "**Ingo Wörner**\nNaststr. 1\n70376 Stuttgart\nGermany"
      }
    ]
  },
  {
    "title": "contact",
    "blocks": [
      {
        "type": "paragraph",
        "text": "[hello@swiss-grid-generator.com](mailto:hello@swiss-grid-generator.com)"
      }
    ]
  },
  {
    "title": "responsible for own content",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Ingo Wörner\nNaststr. 1\n70376 Stuttgart\nGermany"
      }
    ]
  },
  {
    "title": "privacy",
    "blocks": [
      {
        "type": "paragraph",
        "text": "controller: Ingo Wörner. contact: email above."
      },
      {
        "type": "paragraph",
        "text": "processed data:\n- account email\n- authentication data\n- cloud projects\n- feedback\n- screenshots\n- optional support logs\n- service operation data"
      },
      {
        "type": "paragraph",
        "text": "purpose: editor operation, sign-in, cloud storage, feedback, support, security, and synchronization."
      },
      {
        "type": "paragraph",
        "text": "legal bases: contract performance, legitimate interest, and consent where required."
      }
    ]
  },
  {
    "title": "cloud storage",
    "blocks": [
      {
        "type": "paragraph",
        "text": "signed-in users can store projects in Supabase. users remain responsible for project content."
      }
    ]
  },
  {
    "title": "local storage",
    "blocks": [
      {
        "type": "paragraph",
        "text": "the app uses local storage and IndexedDB for preferences, offline cache, local activity, and sync."
      },
      {
        "type": "paragraph",
        "text": "no advertising or analytics cookies are used."
      }
    ]
  },
  {
    "title": "feedback",
    "blocks": [
      {
        "type": "paragraph",
        "text": "feedback is stored in Supabase."
      },
      {
        "type": "paragraph",
        "text": "it may include email, comment, screenshots, app version, and optional support logs."
      },
      {
        "type": "paragraph",
        "text": "use is limited to support and defect review."
      }
    ]
  },
  {
    "title": "user rights",
    "blocks": [
      {
        "type": "paragraph",
        "text": "users may request access, correction, deletion, restriction, portability, or objection by email."
      },
      {
        "type": "paragraph",
        "text": "complaints may be lodged with a competent supervisory authority."
      }
    ]
  },
  {
    "title": "terms of use",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Swiss Grid Generator is provided without guaranteed uninterrupted availability."
      },
      {
        "type": "paragraph",
        "text": "users are responsible for documents, exports, backups, and lawful content use."
      }
    ]
  },
  {
    "title": "consumer dispute resolution",
    "blocks": [
      {
        "type": "paragraph",
        "text": "we do not participate in consumer arbitration proceedings."
      }
    ]
  },
  {
    "title": "note",
    "blocks": [
      {
        "type": "paragraph",
        "text": "this notice is English because the app interface is English."
      }
    ]
  }
] as const satisfies readonly LegalSection[]
