/* eslint-disable */
// This file is generated by webapp/scripts/generate-help-content.mjs from webapp/messages/en/content/help.md.
// Do not edit this file directly.

export type HelpDirectiveName = "APP_VERSION" | "AVAILABLE_FONTS" | "SHORTCUT_TABLE" | "DOCUMENT_VARIABLE_TOKENS"

export type HelpBlock =
  | { type: "paragraph"; text: string }
  | { type: "list"; items: string[] }
  | { type: "directive"; name: HelpDirectiveName }

export type HelpSubsection = {
  id: string
  title: string
  indexed: boolean
  blocks: HelpBlock[]
}

export type HelpSection = {
  id: string
  title: string
  indexed: boolean
  blocks: HelpBlock[]
  subsections: HelpSubsection[]
}

export type HelpGroup = {
  title: string
  sections: HelpSection[]
}

export const HELP_CONTENT_GROUPS = [
  {
    "title": "First sequence",
    "sections": [
      {
        "title": "First sequence",
        "id": "help-quick-start",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Set ratio, orientation, and rotation in `canvas`.",
              "Set the baseline first. It governs the vertical rhythm.",
              "Choose a margin canon or custom baseline-unit frame.",
              "Define columns, rows, gutter, and grid rhythm.",
              "Set type rhythm and base family.",
              "Inspect baselines, margins, modules, typography, and placeholders before export."
            ]
          }
        ],
        "subsections": []
      }
    ]
  },
  {
    "title": "Settings",
    "sections": [
      {
        "title": "Settings reference",
        "id": "help-settings-overview",
        "indexed": false,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Core system controls."
          }
        ],
        "subsections": []
      },
      {
        "title": "Canvas",
        "id": "help-canvas-ratio",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "`ratio` sets page proportion.",
              "Custom ratio preserves A4-equivalent area before orientation is applied.",
              "`orientation` changes the axis.",
              "`rotation` turns the planned page without changing its geometry."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Baseline",
        "id": "help-baseline-grid",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "The baseline is the shared vertical unit.",
              "Type leading, margins, module height, and many movement steps depend on it.",
              "Choose the smallest rhythm that still gives the page calm."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Margins",
        "id": "help-margins",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Margin methods express the content field in baseline units.",
              "Progressive gives a measured lower weight.",
              "Van de Graaf creates a classical asymmetric field.",
              "Baseline gives an equal frame.",
              "Custom margins should be used when the page needs a precise exception."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Grid",
        "id": "help-gutter",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Columns and rows define the modular field.",
              "Gutter multiple sets the distance between modules in baseline units.",
              "Repetitive rhythm is the neutral control.",
              "Non-repetitive rhythms should strengthen proportion, not decorate the page."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Typography",
        "id": "help-typo",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Base family sets the document default.",
              "Type rhythm controls the hierarchy scale.",
              "Fibonacci rhythm can Shift its sequence while remaining tied to the A4 body reference.",
              "Custom type belongs to individual paragraphs, not the global system."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Color",
        "id": "help-color-scheme",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Base scheme defines the placeholder palette.",
              "Page ground is stored per page.",
              "Color is a signal. Use it sparingly."
            ]
          }
        ],
        "subsections": []
      }
    ]
  },
  {
    "title": "General guidance",
    "sections": [
      {
        "title": "General guidance",
        "id": "help-general-overview",
        "indexed": false,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Core editing and layout workflows."
          }
        ],
        "subsections": []
      },
      {
        "title": "Preview workspace",
        "id": "help-preview-workspace",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "The preview is the live layout surface for the active page.",
              "A loaded page appears only after its snapshot and first final page plan are ready.",
              "Double-click inside a module to add text.",
              "`Shift` + double-click adds an image placeholder.",
              "Hold `1..5` while double-clicking to set the new paragraph hierarchy: `1` caption, `2` body, `3` subhead, `4` headline, `5` display.",
              "Hover a layer to reveal edit access and placement guides.",
              "Hovered paragraphs and image placeholders show `>` controls and a bottom-right resize handle.",
              "Controls contain edit, duplicate, and delete. Paragraph controls also expose alignment, rotation, column reflow, hyphenation, column snap, and baseline snap. Image controls expose rotation, column snap, and baseline snap.",
              "Rotation sliders use 5 degree steps while dragging with `Shift`; `Alt/Option` + `Shift` snaps to signed Fibonacci degree stops.",
              "Drag to place, then nudge with arrow keys.",
              "Drag the bottom-right layer handle to resize paragraph or image placeholder rows and columns. `Shift` + drag adjusts height by baseline steps. The handle stays inside the layer frame.",
              "Preview visibility toggles also control export visibility.",
              "Locked layers show guides, but cannot be moved, edited, duplicated, deleted, or retargeted.",
              "`page up`, `page down`, `home`, and `end` navigate pages.",
              "Undo and redo cover settings, content, placement, duplication, deletion, and editor changes."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Text editor",
        "id": "help-editor",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Open from the preview affordance or an unlocked text layer card.",
              "Retarget an open editor by selecting another unlocked paragraph.",
              "The left sidebar switches to `paragraph`, `typography`, `symbols`, `placeholders`, and `info`.",
              "Editor sections remember their open state within the current document.",
              "`Esc` or outside click exits edit mode.",
              "Inline editing follows the rendered line layout."
            ]
          }
        ],
        "subsections": [
          {
            "title": "Paragraph section",
            "id": "help-editor-paragraph",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Set rows, baselines, columns, alignment, reflow, hyphenation, x/y snap, and rotation.",
                  "Height is `rows + baselines`.",
                  "`rows` may be `0` when `baselines` is greater than `0`.",
                  "`rows`, `baselines`, and `cols` preview on hover before commit.",
                  "Rotation uses 5 degree steps with `Shift`; `Alt/Option` + `Shift` snaps to signed Fibonacci degree stops.",
                  "Drag the bottom-right paragraph handle to resize rows and columns. `Shift` + drag adjusts height by baseline steps. The handle stays inside the paragraph frame.",
                  "Column snap locks x to column anchors.",
                  "Baseline snap locks y to the editorial rhythm."
                ]
              }
            ]
          },
          {
            "title": "Typography section",
            "id": "help-editor-typo",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Set family, cut, hierarchy, color, kerning, tracking, and custom size or leading.",
                  "Selecting `custom` seeds size and leading from the paragraph's resolved metrics.",
                  "If text is selected, type and color controls apply to the selection.",
                  "Font, cut, hierarchy, and scheme preview on hover before commit."
                ]
              }
            ]
          },
          {
            "title": "Symbols section",
            "id": "help-editor-symbols",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Insert typographic symbols at the caret or over the current selection.",
                  "The palette includes arrows, bullets, marks, math, Greek lowercase, geometry, and editorial punctuation.",
                  "Symbols export through `Noto Sans Symbols 2` for stable geometry.",
                  "Recent symbols appear after first use."
                ]
              }
            ]
          },
          {
            "title": "Placeholders section",
            "id": "help-editor-placeholders",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Insert document-variable tokens at the caret or over the current selection.",
                  "`<%lorem%>` fills the active frame using current geometry and reflow.",
                  "`<%page%>` and `<%pages%>` use physical page counts. On facing spreads, the right side resolves to the next physical page number.",
                  "Available tokens: {{DOCUMENT_VARIABLE_TOKENS}}."
                ]
              }
            ]
          },
          {
            "title": "Info section",
            "id": "help-editor-info",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Shows geometry, type summary, counts, and maximum line length."
                ]
              }
            ]
          }
        ]
      },
      {
        "title": "Image editor",
        "id": "help-image-editor",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "`Shift` + double-click creates a new image placeholder.",
              "Open from the preview affordance or an unlocked image layer card.",
              "The left sidebar switches to `geometry`, `color`, and `info`.",
              "Editor sections remember their open state within the current document.",
              "`Esc` or outside click exits edit mode."
            ]
          }
        ],
        "subsections": [
          {
            "title": "Geometry section",
            "id": "help-image-editor-geometry",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Set rows, baselines, columns, x/y snap, and rotation.",
                  "Height is `rows + baselines`.",
                  "`rows`, `baselines`, and `cols` preview on hover before commit.",
                  "Hovered image placeholders expose `>` controls for edit, duplicate, delete, rotation, column snap, and baseline snap.",
                  "Rotation uses 5 degree steps with `Shift`; `Alt/Option` + `Shift` snaps to signed Fibonacci degree stops.",
                  "Drag the bottom-right image placeholder handle to resize rows and columns. `Shift` + drag adjusts height by baseline steps. The handle stays inside the placeholder frame."
                ]
              }
            ]
          },
          {
            "title": "Color section",
            "id": "help-image-editor-color",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Set scheme, swatch color, and transparency."
                ]
              }
            ]
          },
          {
            "title": "Info section",
            "id": "help-image-editor-info",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Shows geometry, snap state, rotation, scheme, color, and transparency."
                ]
              }
            ]
          }
        ]
      },
      {
        "title": "Drag and placement",
        "id": "help-drag-placement",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Drag respects each layer's x/y snap settings.",
              "With baseline snap on, normal drag uses module tops.",
              "Hold `Shift` during drag to move y by baseline rows.",
              "Unsnapped layers stay inside allowed placement bounds.",
              "With column snap off, layers may overhang by one column into the side margins.",
              "Selected layers can be moved with arrow keys. `Shift` increases unsnapped movement and switches snapped y to baseline steps."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "History and reflow",
        "id": "help-history-reflow",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Undo and redo cover settings, content, and placement.",
              "Reducing rows or columns never auto-repositions existing layers.",
              "If a grid reduction would push content out of bounds, the change is blocked."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Save and load",
        "id": "help-save-load",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Save stores metadata, pages, settings, layers, and tours.",
              "`save to library` stores a compressed local archive.",
              "`import` restores JSON or `.swissgridgenerator`.",
              "Imported projects require the 2.0 `pages` schema.",
              "Positioned layers use logical anchors so layouts stay stable across grid changes.",
              "Supabase email-code auth is optional and used only for cloud sync."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Export",
        "id": "help-export",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Export supports `JSON`, vector `PDF`, `SVG`, and `IDML`.",
              "Multi-page projects can export a range or explicit page selection.",
              "Export uses current guide visibility.",
              "`PDF`, `SVG`, and `IDML` consume the canonical page plan.",
              "Typography exports as shared glyph-outline geometry in the normal vector path.",
              "`JSON` exports an editable project document with metadata and layout state.",
              "Export metadata can be adjusted without changing the live project unless `JSON` is saved.",
              "Bleed is shared by `PDF`, `SVG`, and `IDML` and changes the export box, not the layout math.",
              "`Esc` closes the dialog when no export is running and cancels an active export at the next safe point."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Project tours",
        "id": "help-project-tours",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "A loaded project may include a guided tour overlay.",
              "Reopen closed tours from `open tour`.",
              "Steps can move between pages, highlight layers, open editors, jump to help topics, or wait for a layer selection."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Layout tooltips",
        "id": "help-layout-tooltips",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Loading a preset or project opens a short workflow note at the bottom of the preview.",
              "`next` advances the sequence.",
              "When help is open, marked tooltip areas jump to their matching help topic on hover."
            ]
          }
        ],
        "subsections": []
      }
    ]
  },
  {
    "title": "Application controls",
    "sections": [
      {
        "title": "Ux reference",
        "id": "help-ux-overview",
        "indexed": false,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Global controls and panel behavior."
          }
        ],
        "subsections": []
      },
      {
        "title": "Application controls",
        "id": "help-application-controls-overview",
        "indexed": false,
        "blocks": [],
        "subsections": []
      },
      {
        "title": "Header and sidebars",
        "id": "help-sidebars-header",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Header actions cover presets, import, save, export, undo, redo, paragraph zoom, display toggles, project, cloud account, and the more menu.",
              "The more menu contains light/dark mode, help, feedback, and legal notice.",
              "The project panel can be toggled with `Cmd/Ctrl+Shift+P`."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Help navigation",
        "id": "help-help-navigation",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Open help, then hover marked targets.",
              "Markers cover header actions, settings panels, preview surface, editor sections, tooltip popup, and preset browser.",
              "Use the up arrow beside a help title to return to the index."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Presets",
        "id": "help-header-examples",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Opens the preset browser.",
              "Bundled files are grouped into `presets` and `examples`.",
              "User files appear under `users` when local or cloud layouts exist.",
              "User storage is local to the browser unless cloud sync is active.",
              "Double-click a thumbnail to load it.",
              "`Esc` closes without loading.",
              "Shortcut: `Cmd/Ctrl+Shift+4`."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Import",
        "id": "help-header-load",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Imports JSON or `.swissgridgenerator`. Shortcut: `Cmd/Ctrl+O`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Save",
        "id": "help-header-save",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Opens `save to library`, then stores the project in the local `users` library. The status dot is red when unsaved, orange when saved locally, and green only when signed in and cloud-synced. Shortcut: `Cmd/Ctrl+S`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Cloud account",
        "id": "help-cloud-account",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Opens the cloud account panel.",
              "The account dot is green only when signed in and fully synced.",
              "Email-code sign-in uses Supabase browser auth.",
              "Signed-in saved projects auto-save locally and sync when possible.",
              "Remote deletions apply locally when no newer unsynced local change exists.",
              "Failures are translated into rate-limit, permission, offline, session, and setup messages."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Export",
        "id": "help-header-export",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Opens export. Shortcut: `Cmd/Ctrl+Shift+E`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Undo",
        "id": "help-header-undo",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Reverts the latest history step. Shortcut: `Cmd/Ctrl+Z`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Redo",
        "id": "help-header-redo",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Reapplies an undone history step. Shortcut: `Cmd/Ctrl+Shift+Z` or `Cmd/Ctrl+Y`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Dark mode",
        "id": "help-header-dark-mode",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Toggles light and dark UI. Shortcut: `Cmd/Ctrl+Shift+D`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Paragraph zoom",
        "id": "help-header-smart-text-zoom",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Toggles zoom-to-paragraph during text editing."
          }
        ],
        "subsections": []
      },
      {
        "title": "Baselines toggle",
        "id": "help-header-baselines",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Shows baseline rhythm. Shortcut: `Cmd/Ctrl+Shift+B`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Margins toggle",
        "id": "help-header-margins",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Shows margin frame. Shortcut: `Cmd/Ctrl+Shift+M`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Modules toggle",
        "id": "help-header-modules",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Shows modular field and gutters. Shortcut: `Cmd/Ctrl+Shift+G`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Typography toggle",
        "id": "help-header-typography",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Shows typography overlay. Shortcut: `Cmd/Ctrl+Shift+T`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Image placeholders toggle",
        "id": "help-header-image-placeholders",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Shows image placeholders. Shortcut: `Cmd/Ctrl+Shift+J`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Project panel",
        "id": "help-header-layers",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Shows project metadata, page order, and page layers. Shortcut: `Cmd/Ctrl+Shift+P`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Information toggle",
        "id": "help-header-information",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Shows contextual help markers. Shortcut: `Cmd/Ctrl+Shift+I`."
          }
        ],
        "subsections": []
      }
    ]
  },
  {
    "title": "Reference",
    "sections": [
      {
        "title": "Fonts",
        "id": "help-reference-fonts",
        "indexed": true,
        "blocks": [
          {
            "type": "directive",
            "name": "AVAILABLE_FONTS"
          }
        ],
        "subsections": []
      },
      {
        "title": "Shortcuts",
        "id": "help-reference-shortcuts",
        "indexed": true,
        "blocks": [
          {
            "type": "directive",
            "name": "SHORTCUT_TABLE"
          }
        ],
        "subsections": []
      }
    ]
  }
] as const satisfies readonly HelpGroup[]

export const HELP_INDEX_GROUPS = [
  {
    "title": "First sequence",
    "items": [
      {
        "id": "help-quick-start",
        "label": "First sequence"
      }
    ]
  },
  {
    "title": "Settings",
    "items": [
      {
        "id": "help-canvas-ratio",
        "label": "Canvas"
      },
      {
        "id": "help-baseline-grid",
        "label": "Baseline"
      },
      {
        "id": "help-margins",
        "label": "Margins"
      },
      {
        "id": "help-gutter",
        "label": "Grid"
      },
      {
        "id": "help-typo",
        "label": "Typography"
      },
      {
        "id": "help-color-scheme",
        "label": "Color"
      }
    ]
  },
  {
    "title": "General guidance",
    "items": [
      {
        "id": "help-preview-workspace",
        "label": "Preview workspace"
      },
      {
        "id": "help-editor",
        "label": "Text editor"
      },
      {
        "id": "help-image-editor",
        "label": "Image editor"
      },
      {
        "id": "help-drag-placement",
        "label": "Drag and placement"
      },
      {
        "id": "help-history-reflow",
        "label": "History and reflow"
      },
      {
        "id": "help-save-load",
        "label": "Save and load"
      },
      {
        "id": "help-export",
        "label": "Export"
      },
      {
        "id": "help-project-tours",
        "label": "Project tours"
      },
      {
        "id": "help-layout-tooltips",
        "label": "Layout tooltips"
      }
    ]
  },
  {
    "title": "Application controls",
    "items": [
      {
        "id": "help-sidebars-header",
        "label": "Header and sidebars"
      },
      {
        "id": "help-help-navigation",
        "label": "Help navigation"
      },
      {
        "id": "help-header-examples",
        "label": "Presets"
      },
      {
        "id": "help-header-load",
        "label": "Import"
      },
      {
        "id": "help-header-save",
        "label": "Save"
      },
      {
        "id": "help-cloud-account",
        "label": "Cloud account"
      },
      {
        "id": "help-header-export",
        "label": "Export"
      },
      {
        "id": "help-header-undo",
        "label": "Undo"
      },
      {
        "id": "help-header-redo",
        "label": "Redo"
      },
      {
        "id": "help-header-dark-mode",
        "label": "Dark mode"
      },
      {
        "id": "help-header-smart-text-zoom",
        "label": "Paragraph zoom"
      },
      {
        "id": "help-header-baselines",
        "label": "Baselines toggle"
      },
      {
        "id": "help-header-margins",
        "label": "Margins toggle"
      },
      {
        "id": "help-header-modules",
        "label": "Modules toggle"
      },
      {
        "id": "help-header-typography",
        "label": "Typography toggle"
      },
      {
        "id": "help-header-image-placeholders",
        "label": "Image placeholders toggle"
      },
      {
        "id": "help-header-layers",
        "label": "Project panel"
      },
      {
        "id": "help-header-information",
        "label": "Information toggle"
      }
    ]
  },
  {
    "title": "Reference",
    "items": [
      {
        "id": "help-reference-fonts",
        "label": "Fonts"
      },
      {
        "id": "help-reference-shortcuts",
        "label": "Shortcuts"
      }
    ]
  }
] as const

export const ALL_HELP_INDEX_ITEMS = [
  {
    "id": "help-quick-start",
    "label": "First sequence"
  },
  {
    "id": "help-settings-overview",
    "label": "Settings reference"
  },
  {
    "id": "help-canvas-ratio",
    "label": "Canvas"
  },
  {
    "id": "help-baseline-grid",
    "label": "Baseline"
  },
  {
    "id": "help-margins",
    "label": "Margins"
  },
  {
    "id": "help-gutter",
    "label": "Grid"
  },
  {
    "id": "help-typo",
    "label": "Typography"
  },
  {
    "id": "help-color-scheme",
    "label": "Color"
  },
  {
    "id": "help-general-overview",
    "label": "General guidance"
  },
  {
    "id": "help-preview-workspace",
    "label": "Preview workspace"
  },
  {
    "id": "help-editor",
    "label": "Text editor"
  },
  {
    "id": "help-image-editor",
    "label": "Image editor"
  },
  {
    "id": "help-drag-placement",
    "label": "Drag and placement"
  },
  {
    "id": "help-history-reflow",
    "label": "History and reflow"
  },
  {
    "id": "help-save-load",
    "label": "Save and load"
  },
  {
    "id": "help-export",
    "label": "Export"
  },
  {
    "id": "help-project-tours",
    "label": "Project tours"
  },
  {
    "id": "help-layout-tooltips",
    "label": "Layout tooltips"
  },
  {
    "id": "help-ux-overview",
    "label": "Ux reference"
  },
  {
    "id": "help-application-controls-overview",
    "label": "Application controls"
  },
  {
    "id": "help-sidebars-header",
    "label": "Header and sidebars"
  },
  {
    "id": "help-help-navigation",
    "label": "Help navigation"
  },
  {
    "id": "help-header-examples",
    "label": "Presets"
  },
  {
    "id": "help-header-load",
    "label": "Import"
  },
  {
    "id": "help-header-save",
    "label": "Save"
  },
  {
    "id": "help-cloud-account",
    "label": "Cloud account"
  },
  {
    "id": "help-header-export",
    "label": "Export"
  },
  {
    "id": "help-header-undo",
    "label": "Undo"
  },
  {
    "id": "help-header-redo",
    "label": "Redo"
  },
  {
    "id": "help-header-dark-mode",
    "label": "Dark mode"
  },
  {
    "id": "help-header-smart-text-zoom",
    "label": "Paragraph zoom"
  },
  {
    "id": "help-header-baselines",
    "label": "Baselines toggle"
  },
  {
    "id": "help-header-margins",
    "label": "Margins toggle"
  },
  {
    "id": "help-header-modules",
    "label": "Modules toggle"
  },
  {
    "id": "help-header-typography",
    "label": "Typography toggle"
  },
  {
    "id": "help-header-image-placeholders",
    "label": "Image placeholders toggle"
  },
  {
    "id": "help-header-layers",
    "label": "Project panel"
  },
  {
    "id": "help-header-information",
    "label": "Information toggle"
  },
  {
    "id": "help-reference-fonts",
    "label": "Fonts"
  },
  {
    "id": "help-reference-shortcuts",
    "label": "Shortcuts"
  }
] as const

export const EDITOR_HELP_SUBSECTION_ITEMS = [
  {
    "id": "help-editor-paragraph",
    "label": "Text editor / Paragraph section"
  },
  {
    "id": "help-editor-typo",
    "label": "Text editor / Typography section"
  },
  {
    "id": "help-editor-symbols",
    "label": "Text editor / Symbols section"
  },
  {
    "id": "help-editor-placeholders",
    "label": "Text editor / Placeholders section"
  },
  {
    "id": "help-editor-info",
    "label": "Text editor / Info section"
  },
  {
    "id": "help-image-editor-geometry",
    "label": "Image editor / Geometry section"
  },
  {
    "id": "help-image-editor-color",
    "label": "Image editor / Color section"
  },
  {
    "id": "help-image-editor-info",
    "label": "Image editor / Info section"
  }
] as const

export const ALL_HELP_SECTION_ITEMS = [
  ...ALL_HELP_INDEX_ITEMS,
  ...EDITOR_HELP_SUBSECTION_ITEMS,
] as const

export type HelpSectionId = (typeof ALL_HELP_SECTION_ITEMS)[number]["id"]
