/* eslint-disable */
// This file is generated by webapp/scripts/generate-legal-content.mjs from webapp/messages/en/content/legal.md.
// Do not edit this file directly.

export type LegalBlock = {
  type: "paragraph"
  text: string
}

export type LegalSection = {
  title: string
  blocks: LegalBlock[]
}

export const LEGAL_CONTENT_SECTIONS = [
  {
    "title": "Legal notice",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Information according to Section 5 DDG."
      }
    ]
  },
  {
    "title": "Provider",
    "blocks": [
      {
        "type": "paragraph",
        "text": "**Ingo Wörner**\nNaststr. 1\n70376 Stuttgart\nGermany"
      }
    ]
  },
  {
    "title": "Contact",
    "blocks": [
      {
        "type": "paragraph",
        "text": "[hello@swiss-grid-generator.com](mailto:hello@swiss-grid-generator.com)"
      }
    ]
  },
  {
    "title": "Responsible for own content",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Ingo Wörner\nNaststr. 1\n70376 Stuttgart\nGermany"
      }
    ]
  },
  {
    "title": "Privacy",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Controller: Ingo Wörner. Contact: email above."
      },
      {
        "type": "paragraph",
        "text": "Processed data:\n- Account email\n- Authentication data\n- Cloud projects\n- Feedback\n- Screenshots\n- Optional support logs\n- Service operation data"
      },
      {
        "type": "paragraph",
        "text": "Purpose: editor operation, sign-in, cloud storage, feedback, support, security, and synchronization."
      },
      {
        "type": "paragraph",
        "text": "Legal bases: contract performance, legitimate interest, and consent where required."
      }
    ]
  },
  {
    "title": "Cloud storage",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Signed-in users can store projects in Supabase. Users remain responsible for project content."
      }
    ]
  },
  {
    "title": "Local storage",
    "blocks": [
      {
        "type": "paragraph",
        "text": "The app uses local storage and IndexedDB for preferences, offline cache, local activity, and sync."
      },
      {
        "type": "paragraph",
        "text": "No advertising or analytics cookies are used."
      }
    ]
  },
  {
    "title": "Feedback",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Feedback is stored in Supabase."
      },
      {
        "type": "paragraph",
        "text": "It may include email, comment, screenshots, app version, and optional support logs."
      },
      {
        "type": "paragraph",
        "text": "Use is limited to support and defect review."
      }
    ]
  },
  {
    "title": "User rights",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Users may request access, correction, deletion, restriction, portability, or objection by email."
      },
      {
        "type": "paragraph",
        "text": "Complaints may be lodged with a competent supervisory authority."
      }
    ]
  },
  {
    "title": "Terms of use",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Swiss Grid Generator is provided without guaranteed uninterrupted availability."
      },
      {
        "type": "paragraph",
        "text": "Users are responsible for documents, exports, backups, and lawful content use."
      }
    ]
  },
  {
    "title": "Consumer dispute resolution",
    "blocks": [
      {
        "type": "paragraph",
        "text": "We do not participate in consumer arbitration proceedings."
      }
    ]
  },
  {
    "title": "Note",
    "blocks": [
      {
        "type": "paragraph",
        "text": "This notice is English because the app interface is English."
      }
    ]
  }
] as const satisfies readonly LegalSection[]
