import test from "node:test"
import assert from "node:assert/strict"
import fs from "node:fs"
import path from "node:path"

const ROOT = process.cwd()

function readText(relPath) {
  return fs.readFileSync(path.join(ROOT, relPath), "utf8")
}

test("idml export rebuilds each project page through the shared resolver and page export plan", () => {
  const source = readText("lib/idml-export.ts")
  const plannedSource = readText("lib/planned-page-export-source.ts")
  assert.match(source, /for\s*\(const\s+\[index,\s*page\]\s+of\s+project\.pages\.entries\(\)\)/)
  assert.match(source, /buildResolvedProjectPageExportSource\(page,\s*sourcePath,\s*\{/)
  assert.match(source, /buildPlannedProjectPageExportSource\(resolved,\s*layoutEngine\)/)
  assert.match(source, /layoutEngine:\s*LayoutEngineContract/)
  assert.match(plannedSource, /buildPageExportPlan\(\{[\s\S]*?showBaselines:\s*source\.uiSettings\.showBaselines/)
  assert.match(plannedSource, /showModules:\s*source\.uiSettings\.showModules/)
  assert.match(plannedSource, /showMargins:\s*source\.uiSettings\.showMargins/)
  assert.match(plannedSource, /showImagePlaceholders:\s*source\.uiSettings\.showImagePlaceholders/)
  assert.match(plannedSource, /showTypography:\s*source\.uiSettings\.showTypography/)
})

test("idml package builder writes a packaged document with resources, spreads, and a backing story", () => {
  const source = readText("lib/idml/builder.ts")
  assert.match(source, /zipSync\(/)
  assert.match(source, /application\/vnd\.adobe\.indesign-idml-package/)
  assert.match(source, /"META-INF\/container\.xml"/)
  assert.match(source, /"META-INF\/metadata\.xml"/)
  assert.match(source, /"Resources\/Graphic\.xml"/)
  assert.match(source, /"Resources\/Fonts\.xml"/)
  assert.match(source, /"Resources\/Styles\.xml"/)
  assert.match(source, /"Resources\/Preferences\.xml"/)
  assert.match(source, /"MasterSpreads\/MasterSpread_sggMaster\.xml"/)
  assert.match(source, /"XML\/BackingStory\.xml"/)
  assert.match(source, /"XML\/Tags\.xml"/)
  assert.match(source, /"designmap\.xml"/)
  assert.match(source, /Spreads\/Spread_\$\{String\(globalPageIndex \+ 1\)\.padStart\(3,\s*"0"\)\}\.xml/)
  assert.match(source, /buildSwissGridIdmlPackageFromPageSets\(document,\s*\[pageSet\],\s*options\)/)
  assert.match(source, /IDML_ZIP_COMPRESSION_LEVEL\s*=\s*1/)
  assert.match(source, /normalizeIdmlZipCompressionLevel\(options\.compressionLevel\)/)
  assert.match(source, /type IdmlZipCompressionLevel = 0 \| 1 \| 2 \| 3 \| 4 \| 5 \| 6 \| 7 \| 8 \| 9/)
})

test("idml builder exposes deterministic page-set artifacts for export-engine workers", () => {
  const source = readText("lib/idml/builder.ts")
  const typesSource = readText("lib/idml/types.ts")
  const engineSource = readText("lib/export-engine.ts")
  const workerSource = readText("workers/idml-page-set.worker.ts")
  const packageWorkerSource = readText("workers/idml-package.worker.ts")
  const cliSource = readText("scripts/export-project.mjs")
  assert.match(typesSource, /export type IdmlPageSetArtifacts/)
  assert.match(source, /export async function buildSwissGridIdmlPageSetArtifacts/)
  assert.match(source, /startPageIndex = 0/)
  assert.match(source, /const globalPageIndex = startPageIndex \+ pageIndex/)
  assert.match(source, /spreads:\s*spreads\.map\(\(spread\):\s*IdmlSpreadArtifact/)
  assert.match(source, /bytes:\s*strToU8\(spread\.xml\)/)
  assert.match(source, /export async function buildSwissGridIdmlPackageFromPageSets/)
  assert.match(source, /orderedPageSets = \[\.\.\.pageSets\]\.sort/)
  assert.match(engineSource, /export function buildExportPageSets<TPage>/)
  assert.match(engineSource, /function runBrowserPageSetWorkers/)
  assert.match(engineSource, /function runSingleBrowserWorker/)
  assert.match(engineSource, /const idmlPageSetCache = new Map/)
  assert.match(engineSource, /getStableRequestCacheKey/)
  assert.match(engineSource, /readPageSetCache\(idmlPageSetCache/)
  assert.match(engineSource, /writePageSetCache\(idmlPageSetCache/)
  assert.match(engineSource, /function cloneIdmlPageSetArtifacts/)
  assert.match(engineSource, /renderIdmlPageSetsWithBrowserWorkers/)
  assert.match(engineSource, /packageIdmlWithBrowserWorker/)
  assert.match(engineSource, /runBrowserPageSetWorkers<IdmlPageSetWorkerRequest,\s*IdmlPageSetWorkerResponse,\s*IdmlPageSetArtifacts>/)
  assert.match(engineSource, /runSingleBrowserWorker<IdmlPackageWorkerRequest,\s*IdmlPackageWorkerResponse,\s*Uint8Array>/)
  assert.match(workerSource, /buildSwissGridIdmlPageSetArtifacts/)
  assert.match(workerSource, /postMessage\([\s\S]*?transfer/)
  assert.match(packageWorkerSource, /buildSwissGridIdmlPackageFromPageSets/)
  assert.match(packageWorkerSource, /postMessage\([\s\S]*?\[bytes\.buffer\]/)
  assert.match(packageWorkerSource, /compressionLevel:\s*request\.compressionLevel/)
  assert.match(cliSource, /--idml-compression-level/)
  assert.match(cliSource, /idmlCompressionLevel/)
})

test("idml builder separates guides, typography, and placeholders on dedicated layers", () => {
  const source = readText("lib/idml/builder.ts")
  assert.match(source, /const\s+LAYER_PLACEHOLDERS_ID\s*=\s*"sggLayerPlaceholders"/)
  assert.match(source, /const\s+LAYER_TYPOGRAPHY_ID\s*=\s*"sggLayerTypography"/)
  assert.match(source, /const\s+LAYER_GUIDES_ID\s*=\s*"sggLayerGuides"/)
  assert.match(source, /ItemLayer:\s*LAYER_PLACEHOLDERS_ID/)
  assert.match(source, /ItemLayer:\s*LAYER_TYPOGRAPHY_ID/)
  assert.match(source, /buildGuideRectanglesXml\(pageTransformMatrix,\s*guideRects\)/)
  assert.match(source, /buildGuideLinesXml\(pageTransformMatrix,\s*guideLines\)/)
  assert.match(source, /layerId:\s*LAYER_GUIDES_ID/)
  assert.match(source, /Name:\s*"Placeholders"/)
  assert.match(source, /Name:\s*"Typography"/)
  assert.match(source, /Name:\s*"Guides"/)
})

test("idml builder places spread items in page coordinates with an explicit page-origin transform", () => {
  const source = readText("lib/idml/builder.ts")
  assert.match(source, /function\s+buildPageCoordinateTransform\(pageHeight:\s*number\):\s*Matrix/)
  assert.match(source, /return\s+\[1,\s*0,\s*0,\s*1,\s*0,\s*-pageHeight\s*\/\s*2\]/)
  assert.match(source, /ItemTransform:\s*formatMatrix\(buildPageCoordinateTransform\(pageHeight\)\)/)
  assert.match(source, /renderRectPathGeometry\(exportBox\.bleed\.x,\s*exportBox\.bleed\.y,\s*exportBox\.bleed\.width,\s*exportBox\.bleed\.height\)/)
})

test("idml designmap declares spreads before section metadata to avoid a synthetic lead page", () => {
  const source = readText("lib/idml/builder.ts")
  assert.match(
    source,
    /\.\.\.spreads\.map\(\(spread\)\s*=>\s*renderIdmlElement\("idPkg:Spread",\s*\{\s*src:\s*spread\.filePath\s*\}\)\),[\s\S]*renderIdmlElement\(\s*"Section"/,
  )
})

test("idml preferences do not predeclare document pages when spreads already define the export range", () => {
  const source = readText("lib/idml/builder.ts")
  assert.doesNotMatch(source, /PagesPerDocument:/)
  assert.match(source, /FacingPages:\s*false/)
})

test("idml export receives shared vector bleed options from the export engine", () => {
  const engineSource = readText("lib/export-engine.ts")
  const builderSource = readText("lib/idml/builder.ts")
  const typesSource = readText("lib/idml/types.ts")
  assert.match(engineSource, /bleedMm:\s*bleedConfig\.enabled\s*\?\s*bleedConfig\.widthMm\s*:\s*0/)
  assert.match(typesSource, /bleedMm\?:\s*number/)
  assert.doesNotMatch(typesSource, /markCanvasMm\?:\s*number/)
  assert.doesNotMatch(typesSource, /cropMarkOffsetMm\?:\s*number/)
  assert.doesNotMatch(typesSource, /cropMarkLengthMm\?:\s*number/)
  assert.match(builderSource, /import\s+\{[\s\S]*?buildExportBox,[\s\S]*?clipExportLineToRect,[\s\S]*?getExportGuideClipRect,[\s\S]*?type\s+ExportLine[\s\S]*?\}\s+from\s+"@\/lib\/export-box"/)
  assert.match(builderSource, /normalizeExportBleedOptions/)
  assert.match(builderSource, /const\s+exportBox\s*=\s*buildExportBox\(\{[\s\S]*?width:\s*pageWidth,[\s\S]*?height:\s*pageHeight,[\s\S]*?bleed:\s*documentBleed/)
  assert.match(builderSource, /getExportGuideClipRect\(exportBox,\s*guideGroup\.clipToPage\)/)
  assert.match(builderSource, /clipExportLineToRect\(line,\s*guideClipRect,\s*guideGroup\.strokeWidth\)/)
  assert.match(builderSource, /Name:\s*"Export Canvas"[\s\S]*?FillColor:\s*COLOR_PAPER_ID/)
  assert.match(builderSource, /function\s+renderLinePathGeometry\(line:\s*ExportLine\)/)
  assert.match(builderSource, /function\s+buildGuideLinesXml\([\s\S]*?"GraphicLine"/)
  assert.match(builderSource, /function\s+renderCropMarkLines\([\s\S]*?cropMarkLines:\s*readonly\s+ExportLine\[\]/)
  assert.match(builderSource, /strokeColorId:\s*COLOR_BLACK_ID,[\s\S]*?name:\s*`Crop mark \$\{lineIndex \+ 1\}`/)
  assert.doesNotMatch(builderSource, /function\s+renderCropMarkRects/)
  assert.match(builderSource, /renderRectPathGeometry\(exportBox\.bleed\.x,\s*exportBox\.bleed\.y,\s*exportBox\.bleed\.width,\s*exportBox\.bleed\.height\)/)
  assert.match(builderSource, /DocumentBleedTopOffset:\s*formatIdmlNumber\(exportBox\.bleedPt\)/)
  assert.match(builderSource, /DocumentSlugTopOffset:\s*formatIdmlNumber\(exportBox\.exportCanvasMarginPt\)/)
  assert.match(builderSource, /DocumentBleedUniformSize:\s*true/)
})

test("idml builder converts shared vector outline geometry into outlined polygon items", () => {
  const source = readText("lib/idml/builder.ts")
  const outlineSource = readText("lib/vector-text-outline.ts")
  assert.match(source, /preloadTextPlanOutlineFonts\(page\.exportPlan\.textPlans\)/)
  assert.match(source, /\(outlineResolver \?\? resolveTextPlanVectorShapes\)\(textPlan\)/)
  assert.match(source, /for\s*\(const\s+\[shapeIndex,\s*shape\]\s+of\s+outlineShapes\.entries\(\)\)/)
  assert.match(source, /convertOpenTypeCommandsToGeometryPaths\(shape\.commands\)/)
  assert.match(source, /renderIdmlElement\(\s*"Polygon"/)
  assert.match(source, /renderPathGeometry\(geometryPaths\)/)
  assert.match(outlineSource, /loadOutlineFont\(fontFamily,\s*fontWeight,\s*italic\)/)
  assert.match(outlineSource, /outlineFont\.getPath\(/)
})

test("idml styles still include paragraph families plus per-character vector export resources", () => {
  const source = readText("lib/idml/builder.ts")
  assert.match(source, /buildCharacterStyles\(/)
  assert.match(source, /buildParagraphStyleKeys\(/)
  assert.match(source, /"body",\s*"headline",\s*"display",\s*"fx",\s*"caption"/)
  assert.match(source, /CharacterStyle\/sgg\/char_/)
  assert.match(source, /ParagraphStyle\/sgg\//)
  assert.match(source, /AppliedFont",\s*\{\s*type:\s*"string"\s*\}/)
  assert.match(source, /Leading",\s*\{\s*type:\s*"unit"\s*\}/)
})

test("idml font metadata prefers parsed font-file names and keeps a fallback path", () => {
  const source = readText("lib/idml/font-metadata.ts")
  assert.match(source, /findTable\(view,\s*"name"\)/)
  assert.match(source, /const\s+nameId\s*=\s*view\.getUint16\(recordOffset\s*\+\s*6,\s*false\)/)
  assert.match(source, /byNameId\.get\(16\)/)
  assert.match(source, /byNameId\.get\(17\)/)
  assert.match(source, /byNameId\.get\(6\)/)
  assert.match(source, /getFontAssetPath\(fontFamily,\s*resolvedVariant\.weight,\s*resolvedVariant\.italic\)/)
  assert.match(source, /buildFallbackMetadata\(/)
})
