import test from "node:test"
import assert from "node:assert/strict"
import fs from "node:fs"
import path from "node:path"

const ROOT = process.cwd()

function readText(relPath) {
  return fs.readFileSync(path.join(ROOT, relPath), "utf8")
}

test("page navigation centralizes the settled GUI page separately from immediate preview selection", () => {
  const hookSource = readText("hooks/useSettledPageNavigation.ts")
  const pageSource = readText("gui/shell/useShellModel.tsx")
  const workspaceSource = readText("components/preview/PreviewWorkspace.tsx")
  const panelSource = readText("components/sidebar/PagesPanel.tsx")
  const layerListSource = readText("components/sidebar/ProjectPageLayersList.tsx")

  assert.match(hookSource, /export\s+const\s+PAGE_GUI_SETTLE_DELAY_MS\s*=\s*500/)
  assert.match(hookSource, /pendingSettledPageTargetRef/)
  assert.match(hookSource, /const\s+\[settledPages,\s*setSettledPages\]\s*=\s*useState<readonly\s+TPage\[\]>\(pages\)/)
  assert.match(hookSource, /latestPagesRef/)
  assert.match(hookSource, /requestSettledPageFocus/)
  assert.match(hookSource, /setSettledPages\(latestPagesRef\.current\)[\s\S]*?setSettledPageId\(pageId\)/)
  assert.match(hookSource, /window\.setTimeout\([\s\S]*?setSettledPageId\(pageId\)[\s\S]*?settleDelayMs/)
  assert.match(hookSource, /settledPages,/)
  assert.doesNotMatch(hookSource, /structuredClone|cloneSettledPagesSnapshot/)

  assert.match(pageSource, /useSettledPageNavigation\(\{[\s\S]*?activePageId,[\s\S]*?pages:\s*liveProjectPages/)
  assert.match(pageSource, /requestSettledPageFocus\(nextPageId\)[\s\S]*?selectPage\(nextPageId\)/)
  assert.match(pageSource, /const\s+handleDirectProjectPageSelect\s*=\s*useCallback\(\(pageId:\s*string\)/)
  assert.match(pageSource, /requestSettledPageFocus\(pageId\)[\s\S]*?selectPage\(pageId\)/)
  assert.doesNotMatch(pageSource, /commitSettledPage\(pageId\)/)
  assert.match(pageSource, /const\s+sidebarControlsUseLivePage\s*=\s*sidebarActivePageId\s*===\s*activePageId\s*&&\s*!isPageGuiSettling/)
  assert.match(pageSource, /const\s+sidebarControlUi\s*=\s*useMemo<UiSettingsSnapshot>/)
  assert.match(pageSource, /resolveUiSettingsSnapshot\(sidebarActivePage\.uiSettings\)/)
  assert.match(pageSource, /const\s+liveProjectPages\s*=\s*useMemo\(\(\)\s*=>\s*\{[\s\S]*?page\.id\s*===\s*activePage\.id\s*\?\s*activePage\s*:\s*page/)
  assert.match(pageSource, /useSettledPageNavigation\(\{[\s\S]*?pages:\s*liveProjectPages/)
  assert.match(pageSource, /interactionsDisabled=\{showPresetsBrowser\s*\|\|\s*!sidebarControlsUseLivePage\}/)
  assert.match(pageSource, /sidebarActiveProjectPage=\{sidebarActivePage\}/)
  assert.match(pageSource, /sidebarActivePageId=\{sidebarActivePageId\}/)
  assert.match(pageSource, /sidebarControlsUseLivePage=\{sidebarControlsUseLivePage\}/)
  assert.match(pageSource, /settledPages:\s*sidebarProjectPages/)
  assert.match(pageSource, /const\s+sidebarProjectPageItems\s*=\s*useMemo\(\(\)\s*=>\s*\(/)
  assert.match(pageSource, /projectPages=\{sidebarProjectPageItems\}/)
  assert.match(pageSource, /projectInfoPages=\{projectPages\}/)

  assert.match(workspaceSource, /sidebarActiveProjectPage:\s*PreviewProjectPage\s*\|\s*null/)
  assert.match(workspaceSource, /sidebarActivePageId:\s*string/)
  assert.match(workspaceSource, /sidebarControlsUseLivePage:\s*boolean/)
  assert.match(workspaceSource, /projectPages:\s*readonly\s+PreviewProjectPageListItem\[\]/)
  assert.match(workspaceSource, /projectInfoPages:\s*readonly\s+PreviewProjectPage\[\]/)
  assert.match(workspaceSource, /activePage=\{sidebarActiveProjectPage\}/)
  assert.match(workspaceSource, /activePageId=\{sidebarActivePageId\}/)
  assert.match(workspaceSource, /const\s+settledLayerPanelStateRef\s*=\s*useRef\(liveLayerPanelState\)/)
  assert.match(workspaceSource, /if\s*\(sidebarControlsUseLivePage\)\s*\{[\s\S]*?settledLayerPanelStateRef\.current\s*=\s*liveLayerPanelState/)
  assert.match(workspaceSource, /const\s+layerPanelState\s*=\s*sidebarControlsUseLivePage[\s\S]*?settledLayerPanelStateRef\.current/)
  assert.match(workspaceSource, /const\s+pagesPanelElement\s*=\s*useMemo\(\(\)\s*=>\s*\(/)
  assert.match(workspaceSource, /const\s+\[pageListRequestToken,\s*setPageListRequestToken\]\s*=\s*useState\(0\)/)
  assert.match(workspaceSource, /const\s+\[pageNumberEditing,\s*setPageNumberEditing\]\s*=\s*useState\(false\)/)
  assert.match(workspaceSource, /const\s+pageNumberInputRef\s*=\s*useRef<HTMLInputElement\s*\|\s*null>\(null\)/)
  assert.match(workspaceSource, /pageListRequestToken=\{pageListRequestToken\}/)
  assert.match(workspaceSource, /Show page list\\nClick P A G E S to return from a page submenu to the page list\./)
  assert.match(workspaceSource, /tooltipClassName="[^"]*normal-case[^"]*tracking-normal[^"]*"/)
  assert.doesNotMatch(workspaceSource, /Click PAGES/)
  assert.match(workspaceSource, /<span>P A G E S<\/span>/)
  assert.match(workspaceSource, /function\s+requestPageListView\(\)\s*\{[\s\S]*?setPageListRequestToken\(\(current\)\s*=>\s*current\s*\+\s*1\)/)
  assert.match(workspaceSource, /onRowClick=\{isSingleProjectPage\s*\?\s*undefined\s*:\s*requestPageListView\}/)
  assert.match(workspaceSource, /function\s+resolveProjectPageIdForPhysicalPage\(pageNumber:\s*number\)/)
  assert.match(workspaceSource, /getProjectPagePhysicalPageSpan\(page\)/)
  assert.match(workspaceSource, /function\s+beginPageNumberEdit\(\)/)
  assert.match(workspaceSource, /function\s+commitPageNumberEdit\(\)/)
  assert.match(workspaceSource, /function\s+selectPhysicalPage\(pageNumber:\s*number\)/)
  assert.match(workspaceSource, /const\s+renderPageNavigationButton\s*=\s*\(/)
  assert.match(workspaceSource, /aria-label=\{label\}[\s\S]*?onClick=\{\(\)\s*=>\s*selectPhysicalPage\(targetPageNumber\)\}/)
  assert.match(workspaceSource, /"First page"[\s\S]*?<ChevronsLeft/)
  assert.match(workspaceSource, /"Previous page"[\s\S]*?<ChevronLeft/)
  assert.match(workspaceSource, /"Next page"[\s\S]*?<ChevronRight/)
  assert.match(workspaceSource, /"Last page"[\s\S]*?<ChevronsRight/)
  assert.match(workspaceSource, /onDoubleClick=\{beginPageNumberEdit\}/)
  assert.match(workspaceSource, /Double-click the current page number to jump to a page\./)
  assert.match(workspaceSource, /<span className="min-w-0 truncate text-\[11px\] font-normal leading-none">\s*\{pagePositionValue\}\s*<\/span>/)
  assert.match(workspaceSource, /<button[\s\S]*?>\s*\{documentPagePosition\}\s*<\/button>/)
  assert.match(workspaceSource, /<span className="px-1">of<\/span>/)
  assert.doesNotMatch(workspaceSource, /Page\s*\{documentPagePosition\}\s*of\s*\{documentVariablePageCount\}/)
  assert.match(workspaceSource, /if\s*\(event\.shiftKey\)\s*\{[\s\S]*?onPageAddWithContent\(\)/)
  assert.match(workspaceSource, /const\s+\[pageAddHovered,\s*setPageAddHovered\]\s*=\s*useState\(false\)/)
  assert.match(workspaceSource, /function\s+renderPageAddActions\(\)/)
  assert.match(workspaceSource, /Shift-click duplicates page with content/)
  assert.match(workspaceSource, /Maximum \$\{MAX_GUI_PROJECT_PAGES\} pages reached\./)
  assert.doesNotMatch(workspaceSource, /Add page copy with content|Maximum \$\{MAX_GUI_PROJECT_PAGES\} pages`\s*:\s*"\+\+/)
  assert.doesNotMatch(workspaceSource, /label="Add Page"|>\s*Add\s*<\/span>|renderPageAddActions\("footer"\)|grid-rows-\[max-content_minmax\(0,1fr\)_auto\]/)
  assert.match(workspaceSource, /baseFont,\s*[\r\n]\s*imageColorScheme,\s*[\r\n]\s*selectedLayerKey,/)
  assert.match(workspaceSource, /const\s+documentVariablePageCount\s*=\s*useMemo\(\s*\(\)\s*=>\s*getProjectPhysicalPageCount\(projectPages\)/)
  assert.match(workspaceSource, /const\s+documentPagePosition\s*=\s*Math\.min\(Math\.max\(activePageNumber,\s*1\),\s*documentVariablePageCount\)/)
  assert.match(workspaceSource, /const\s+documentPagePositionPercent\s*=\s*documentVariablePageCount\s*<=\s*1/)
  assert.match(workspaceSource, /className="pointer-events-none fixed left-0 right-0 top-0 z-50 h-px overflow-hidden"/)
  assert.match(workspaceSource, /style=\{\{\s*width:\s*`\$\{documentPagePositionPercent\}%`\s*\}\}/)
  assert.match(workspaceSource, /aria-label=\{`Page position \$\{documentPagePosition\} of \$\{documentVariablePageCount\}`\}/)
  assert.match(workspaceSource, /role="progressbar"/)
  assert.match(workspaceSource, /aria-valuenow=\{documentPagePosition\}/)
  assert.match(workspaceSource, /aria-disabled=\{!sidebarControlsUseLivePage\}/)
  assert.match(workspaceSource, /grid\s+h-full\s+min-h-0\s+grid-rows-\[max-content_minmax\(0,1fr\)\]/)
  assert.match(workspaceSource, /data-help-scroll-root="true"[\s\S]*?className="min-h-0 overflow-y-auto overscroll-contain/)
  assert.match(workspaceSource, /\[scrollbar-gutter:stable\]/)
  assert.match(workspaceSource, /sidebarControlsUseLivePage\s*\?\s*""\s*:\s*"pointer-events-none opacity-50"/)
  assert.match(workspaceSource, /baseFont=\{layerPanelState\.baseFont\}/)
  assert.match(workspaceSource, /imageColorScheme=\{layerPanelState\.imageColorScheme\}/)
  assert.match(workspaceSource, /selectedLayerKey=\{layerPanelState\.selectedLayerKey\}/)
  assert.match(workspaceSource, /previewHoveredLayerKey=\{layerPanelState\.previewHoveredLayerKey\}/)
  assert.match(workspaceSource, /\),\s*\[[\s\S]*?layerPanelState,[\s\S]*?projectPages,[\s\S]*?sidebarActivePageId,[\s\S]*?sidebarActiveProjectPage,[\s\S]*?\]\)/)
  assert.match(workspaceSource, /\{pagesPanelElement\}/)
  assert.match(panelSource, /const\s+\[manualExpandedPageId,\s*setManualExpandedPageId\]\s*=\s*useState<string\s*\|\s*null>\(null\)/)
  assert.match(panelSource, /const\s+\[transientExpandedPageId,\s*setTransientExpandedPageId\]\s*=\s*useState<string\s*\|\s*null>\(\(\)\s*=>\s*\(/)
  assert.match(panelSource, /pageListRequestToken\?:\s*number/)
  assert.match(panelSource, /const\s+\[forcePageListView,\s*setForcePageListView\]\s*=\s*useState\(\(\)\s*=>\s*pages\.length\s*>\s*1\)/)
  assert.match(panelSource, /type\s+PendingPageScrollTarget\s*=\s*\{[\s\S]*?behavior\?:\s*ScrollBehavior/)
  assert.match(panelSource, /lastPageListRequestTokenRef/)
  assert.match(panelSource, /selectionOnlyPageIdRef/)
  assert.match(panelSource, /pendingPageClickTimerRef/)
  assert.match(panelSource, /lastPageClickRef/)
  assert.match(panelSource, /function|const\s+clearPendingPageClick/)
  assert.match(panelSource, /window\.clearTimeout\(pendingPageClickTimerRef\.current\)/)
  assert.match(panelSource, /pendingPageClickTimerRef\.current\s*=\s*window\.setTimeout\([\s\S]*?selectionOnlyPageIdRef\.current\s*=\s*page\.id[\s\S]*?onSelectPage\(page\.id\)[\s\S]*?,\s*180\)/)
  assert.match(panelSource, /if\s*\(selectionOnlyPageIdRef\.current\s*===\s*activePageId\)\s*\{[\s\S]*?setForcePageListView\(true\)[\s\S]*?return/)
  assert.match(panelSource, /if\s*\(renderPageList\)\s*\{[\s\S]*?selectionOnlyPageIdRef\.current\s*=\s*page\.id/)
  assert.match(panelSource, /const\s+openPageSubmenu\s*=\s*\(pageId:\s*string\)\s*=>\s*\{[\s\S]*?setManualExpandedPageId\(pageId\)/)
  assert.match(panelSource, /const\s+closePageSubmenuToList\s*=\s*\(pageId:\s*string\)\s*=>\s*\{[\s\S]*?pendingScrollTargetRef\.current\s*=\s*\{\s*pageId,\s*behavior:\s*"auto"\s*\}[\s\S]*?setForcePageListView\(true\)/)
  assert.match(panelSource, /pendingScrollTargetRef\.current\s*=\s*\{\s*pageId:\s*expandedPageId\s*\?\?\s*activePageId,\s*behavior:\s*"auto",?\s*\}/)
  assert.match(panelSource, /event\.detail\s*>=\s*2\s*\|\|\s*isRepeatedListClick/)
  assert.match(panelSource, /if\s*\(event\.detail\s*>=\s*2\s*\|\|\s*isRepeatedListClick\)\s*\{[\s\S]*?openPageSubmenu\(page\.id\)/)
  assert.match(panelSource, /aria-label=\{isExpanded\s*\?\s*`Collapse \$\{page\.name\}`\s*:\s*`Expand \$\{page\.name\}`\}[\s\S]*?onSelectPage\(page\.id\)[\s\S]*?openPageSubmenu\(page\.id\)/)
  const pageDoubleClickHandlerMatch = panelSource.match(/onDoubleClick=\{\(\) => \{[\s\S]*?\n          \}\}/)
  assert.ok(pageDoubleClickHandlerMatch)
  assert.match(pageDoubleClickHandlerMatch[0], /if\s*\(isExpanded\)\s*return/)
  assert.doesNotMatch(pageDoubleClickHandlerMatch[0], /setForcePageListView\(true\)|closePageSubmenuToList/)
  assert.match(panelSource, /setForcePageListView\(true\)/)
  assert.match(panelSource, /useLayoutEffect\(\(\)\s*=>\s*\{[\s\S]*?if\s*\(renderPageList\)\s*return[\s\S]*?scrollRoot\.scrollTop\s*=\s*0/)
  assert.match(panelSource, /if\s*\(!renderPageList\)\s*\{[\s\S]*?scrollRoot\.scrollTop\s*=\s*0[\s\S]*?pendingScrollTargetRef\.current\s*=\s*null/)
  assert.match(panelSource, /const\s+renderPageList\s*=\s*expandedPage\s*===\s*null/)
  assert.match(panelSource, /const\s+virtualizationEnabled\s*=\s*renderPageList[\s\S]*?pages\.length\s*>=\s*PAGE_VIRTUALIZATION_THRESHOLD/)
  assert.match(panelSource, /if\s*\(!renderPageList\)\s*\{[\s\S]*?totalHeight:\s*0/)
  assert.match(panelSource, /renderPageList\s*\?\s*pages\s*:\s*expandedPage[\s\S]*?\?\s*\[expandedPage\]/)
  assert.match(panelSource, /setTransientExpandedReason\("page-navigation"\)/)
  assert.match(panelSource, /draggable=\{!isEditing\s*&&\s*!isExpanded\}/)
  assert.match(panelSource, /if\s*\(isEditing\)\s*return/)
  assert.match(panelSource, /truncate\s+text-\[12px\]\s+font-normal\s+leading-none/)
  assert.doesNotMatch(panelSource, /truncate\s+text-\[12px\]\s+font-medium\s+leading-none/)
  assert.match(panelSource, /const\s+lastPanelActivePageIdRef\s*=\s*useRef\(activePageId\)/)
  assert.match(panelSource, /if\s*\(lastPanelActivePageIdRef\.current\s*===\s*activePageId\)\s*return/)
  assert.match(panelSource, /setTransientExpandedPageId\(activePageId\)/)
  assert.match(panelSource, /selectedLayerKey=\{isActive\s*\?\s*selectedLayerKey\s*:\s*null\}/)
  assert.doesNotMatch(panelSource, /data-page-layers-scroll-root|max-h-\[min\(60vh,28rem\)\]/)
  assert.match(layerListSource, /if\s*\(!selectedLayerKey\s*\|\|\s*!isActivePage\)\s*return/)
  assert.match(layerListSource, /const\s+allowLayerInteractions\s*=\s*isActivePage\s*&&\s*!isLocked/)
  assert.match(layerListSource, /LOCK_BUTTON_DOUBLE_CLICK_WINDOW_MS\s*=\s*320/)
  assert.match(layerListSource, /lastLockButtonClickRef/)
  assert.match(layerListSource, /const\s+isRepeatedLockClick\s*=[\s\S]*?LOCK_BUTTON_DOUBLE_CLICK_WINDOW_MS/)
  assert.match(layerListSource, /if\s*\(event\.detail\s*>=\s*2\s*\|\|\s*isRepeatedLockClick\)\s*\{[\s\S]*?onToggleAllLocks\(pageId,\s*previousClick\?\.targetLocked\s*\?\?\s*!isLocked\)[\s\S]*?return/)
  assert.match(layerListSource, /const\s+targetLocked\s*=\s*!isLocked[\s\S]*?onToggleLock\(thumb\.key,\s*targetLocked\)/)
  assert.match(layerListSource, /onDoubleClick=\{\(event\)\s*=>\s*\{\s*event\.stopPropagation\(\)\s*\}\}/)
  assert.doesNotMatch(layerListSource, new RegExp([
    "LOCK_BUTTON_CLICK_" + "DELAY_MS",
    "lockButtonClick" + "TimeoutRef",
    "consumedLockButton" + "DoubleClickRef",
    "window\\.setTimeout\\(\\(\\)\\s*=>\\s*\\{[\\s\\S]*?onToggleLock",
  ].join("|")))

  assert.doesNotMatch(workspaceSource, /activePageFocusRequest/)
  assert.doesNotMatch(workspaceSource, /interactionsDisabled=\{!sidebarControlsUseLivePage\}/)
  assert.doesNotMatch(panelSource, /activePageFocusRequest/)
  assert.doesNotMatch(panelSource, /interactionsDisabled|panelUiActive/)
  assert.doesNotMatch(layerListSource, /interactionsDisabled|layerUiActive/)
  assert.doesNotMatch(panelSource, /KEYBOARD_PAGE_SETTLE_DELAY_MS/)
  assert.doesNotMatch(panelSource, /scheduledKeyboardFocusRequest/)
  assert.doesNotMatch(panelSource, /deferredKeyboardActivePageId/)
})
