import test from "node:test"
import assert from "node:assert/strict"
import fs from "node:fs"
import path from "node:path"

const ROOT = process.cwd()

function readText(relPath) {
  return fs.readFileSync(path.join(ROOT, relPath), "utf8")
}

test("page navigation centralizes the settled GUI page separately from immediate preview selection", () => {
  const hookSource = readText("hooks/useSettledPageNavigation.ts")
  const pageSource = readText("app/page.tsx")
  const workspaceSource = readText("components/preview/PreviewWorkspace.tsx")
  const panelSource = readText("components/sidebar/PagesPanel.tsx")
  const layerListSource = readText("components/sidebar/ProjectPageLayersList.tsx")

  assert.match(hookSource, /export\s+const\s+PAGE_GUI_SETTLE_DELAY_MS\s*=\s*500/)
  assert.match(hookSource, /pendingSettledPageTargetRef/)
  assert.match(hookSource, /const\s+\[settledPages,\s*setSettledPages\]\s*=\s*useState<readonly\s+TPage\[\]>\(pages\)/)
  assert.match(hookSource, /latestPagesRef/)
  assert.match(hookSource, /requestSettledPageFocus/)
  assert.match(hookSource, /setSettledPages\(latestPagesRef\.current\)[\s\S]*?setSettledPageId\(pageId\)/)
  assert.match(hookSource, /window\.setTimeout\([\s\S]*?setSettledPageId\(pageId\)[\s\S]*?settleDelayMs/)
  assert.match(hookSource, /settleGuiPageNow/)
  assert.match(hookSource, /settledPages,/)
  assert.doesNotMatch(hookSource, /structuredClone|cloneSettledPagesSnapshot/)

  assert.match(pageSource, /useSettledPageNavigation\(\{[\s\S]*?activePageId,[\s\S]*?pages:\s*projectPages/)
  assert.match(pageSource, /requestSettledPageFocus\(nextPageId\)[\s\S]*?selectPage\(nextPageId\)/)
  assert.match(pageSource, /const\s+handleDirectProjectPageSelect\s*=\s*useCallback\(\(pageId:\s*string\)/)
  assert.match(pageSource, /requestSettledPageFocus\(pageId\)[\s\S]*?selectPage\(pageId\)/)
  assert.doesNotMatch(pageSource, /settleGuiPageNow\(pageId\)/)
  assert.match(pageSource, /const\s+sidebarControlsUseLivePage\s*=\s*sidebarActivePageId\s*===\s*activePageId\s*&&\s*!isPageGuiSettling/)
  assert.match(pageSource, /const\s+sidebarControlUi\s*=\s*useMemo<UiSettingsSnapshot>/)
  assert.match(pageSource, /resolveUiSettingsSnapshot\(sidebarActivePage\.uiSettings\)/)
  assert.match(pageSource, /interactionsDisabled=\{showPresetsBrowser\s*\|\|\s*!sidebarControlsUseLivePage\}/)
  assert.match(pageSource, /sidebarActiveProjectPage=\{sidebarActivePage\}/)
  assert.match(pageSource, /sidebarActivePageId=\{sidebarActivePageId\}/)
  assert.match(pageSource, /sidebarControlsUseLivePage=\{sidebarControlsUseLivePage\}/)
  assert.match(pageSource, /settledPages:\s*sidebarProjectPages/)
  assert.match(pageSource, /projectPages=\{sidebarProjectPages\}/)

  assert.match(workspaceSource, /sidebarActiveProjectPage:\s*PreviewProjectPage\s*\|\s*null/)
  assert.match(workspaceSource, /sidebarActivePageId:\s*string/)
  assert.match(workspaceSource, /sidebarControlsUseLivePage:\s*boolean/)
  assert.match(workspaceSource, /projectPages:\s*readonly\s+PreviewProjectPage\[\]/)
  assert.match(workspaceSource, /activePage=\{sidebarActiveProjectPage\}/)
  assert.match(workspaceSource, /activePageId=\{sidebarActivePageId\}/)
  assert.match(workspaceSource, /const\s+settledLayerPanelStateRef\s*=\s*useRef\(liveLayerPanelState\)/)
  assert.match(workspaceSource, /if\s*\(sidebarControlsUseLivePage\)\s*\{[\s\S]*?settledLayerPanelStateRef\.current\s*=\s*liveLayerPanelState/)
  assert.match(workspaceSource, /const\s+layerPanelState\s*=\s*sidebarControlsUseLivePage[\s\S]*?settledLayerPanelStateRef\.current/)
  assert.match(workspaceSource, /aria-disabled=\{!sidebarControlsUseLivePage\}/)
  assert.match(workspaceSource, /sidebarControlsUseLivePage\s*\?\s*""\s*:\s*"pointer-events-none opacity-50"/)
  assert.match(workspaceSource, /selectedLayerKey=\{layerPanelState\.selectedLayerKey\}/)
  assert.match(workspaceSource, /previewHoveredLayerKey=\{layerPanelState\.previewHoveredLayerKey\}/)
  assert.match(panelSource, /useState<string\s*\|\s*null>\(activePageId\)/)
  assert.match(panelSource, /const\s+renderPageList\s*=\s*expandedPage\s*===\s*null/)
  assert.match(panelSource, /const\s+virtualizationEnabled\s*=\s*renderPageList[\s\S]*?pages\.length\s*>=\s*PAGE_VIRTUALIZATION_THRESHOLD/)
  assert.match(panelSource, /renderPageList\s*\?\s*pages\s*:\s*expandedPage[\s\S]*?\?\s*\[expandedPage\]/)
  assert.match(panelSource, /setTransientExpandedReason\("page-navigation"\)/)
  assert.match(panelSource, /draggable=\{!isEditing\s*&&\s*!isExpanded\}/)
  assert.match(panelSource, /if\s*\(isEditing\)\s*return/)
  assert.match(panelSource, /const\s+lastPanelActivePageIdRef\s*=\s*useRef\(activePageId\)/)
  assert.match(panelSource, /if\s*\(lastPanelActivePageIdRef\.current\s*===\s*activePageId\)\s*return/)
  assert.match(panelSource, /setTransientExpandedPageId\(activePageId\)/)
  assert.match(panelSource, /selectedLayerKey=\{isActive\s*\?\s*selectedLayerKey\s*:\s*null\}/)
  assert.match(layerListSource, /if\s*\(!selectedLayerKey\s*\|\|\s*!isActivePage\)\s*return/)
  assert.match(layerListSource, /const\s+allowLayerInteractions\s*=\s*isActivePage\s*&&\s*!isLocked/)

  assert.doesNotMatch(workspaceSource, /activePageFocusRequest/)
  assert.doesNotMatch(workspaceSource, /interactionsDisabled=\{!sidebarControlsUseLivePage\}/)
  assert.doesNotMatch(panelSource, /activePageFocusRequest/)
  assert.doesNotMatch(panelSource, /interactionsDisabled|panelUiActive/)
  assert.doesNotMatch(layerListSource, /interactionsDisabled|layerUiActive/)
  assert.doesNotMatch(panelSource, /KEYBOARD_PAGE_SETTLE_DELAY_MS/)
  assert.doesNotMatch(panelSource, /scheduledKeyboardFocusRequest/)
  assert.doesNotMatch(panelSource, /deferredKeyboardActivePageId/)
})
