/* eslint-disable */
// This file is generated by webapp/scripts/generate-tooltip-content.mjs from webapp/messages/en/content/tooltips.md.
// Do not edit this file directly.

export type TooltipBlock =
  | { type: "paragraph"; text: string }
  | { type: "list"; items: string[] }

export type LayoutOpenTooltipItem = {
  id: string
  title: string
  blocks: TooltipBlock[]
}

export const LAYOUT_OPEN_TOOLTIP_ITEMS = [
  {
    "id": "tooltip-start-with-system",
    "title": "start with the page system",
    "blocks": [
      {
        "type": "paragraph",
        "text": "set canvas, baseline, margins, modular field, rhythm, type scale, and base family before placing many layers."
      },
      {
        "type": "paragraph",
        "text": "if the page feels unresolved, adjust the system first. local paragraph changes are useful only after the field is stable."
      }
    ]
  },
  {
    "id": "tooltip-structure-before-styling",
    "title": "structure before styling",
    "blocks": [
      {
        "type": "paragraph",
        "text": "use `rows`, `baselines`, and `cols` to define the text frame before refining wording, tracking, or color."
      },
      {
        "type": "paragraph",
        "text": "the frame is the editorial decision. styling should clarify it, not compensate for it."
      }
    ]
  },
  {
    "id": "tooltip-repetitive-reference",
    "title": "use repetitive as a control",
    "blocks": [
      {
        "type": "paragraph",
        "text": "judge the page first in `repetitive` rhythm. it gives the clearest reading of margins, baseline, hierarchy, and measure."
      },
      {
        "type": "paragraph",
        "text": "use fibonacci, golden ratio, perfect fourth, or perfect fifth only when asymmetry strengthens the field."
      }
    ]
  },
  {
    "id": "tooltip-create-text",
    "title": "create text on the grid",
    "blocks": [
      {
        "type": "paragraph",
        "text": "double-click inside a module to create a paragraph where the structure suggests it belongs."
      },
      {
        "type": "paragraph",
        "text": "the block starts on the clicked module, with hyphenation off, and clamps to the available columns."
      }
    ]
  },
  {
    "id": "tooltip-create-hierarchy",
    "title": "choose hierarchy while creating",
    "blocks": [
      {
        "type": "paragraph",
        "text": "hold `1..5` while double-clicking to assign hierarchy immediately."
      },
      {
        "type": "paragraph",
        "text": "`1` caption, `2` body, `3` subhead, `4` headline, `5` display. the initial measure follows the role and the remaining column field."
      }
    ]
  },
  {
    "id": "tooltip-create-image",
    "title": "place image placeholders deliberately",
    "blocks": [
      {
        "type": "paragraph",
        "text": "use `shift` + double-click on an empty module to create an image placeholder."
      },
      {
        "type": "paragraph",
        "text": "placeholders share the same snap, span, baseline height, and rotation discipline as text."
      }
    ]
  },
  {
    "id": "tooltip-lorem-frame-test",
    "title": "use lorem as a frame test",
    "blocks": [
      {
        "type": "paragraph",
        "text": "insert `<%lorem%>` to test whether a paragraph frame can carry the intended density."
      },
      {
        "type": "paragraph",
        "text": "the token fills the active frame using current rows, baselines, columns, reflow, and hyphenation."
      }
    ]
  },
  {
    "id": "tooltip-drag-and-nudge",
    "title": "drag for placement, nudge for decision",
    "blocks": [
      {
        "type": "paragraph",
        "text": "drag to establish position. use cursor keys for final placement."
      },
      {
        "type": "paragraph",
        "text": "nudging follows the same logical grid model as dragging, so movement stays tied to the page system."
      }
    ]
  },
  {
    "id": "tooltip-cursor-nudge",
    "title": "nudge with the grid",
    "blocks": [
      {
        "type": "paragraph",
        "text": "with snapped axes enabled, arrow keys move the selected unlocked layer by columns and module rows."
      },
      {
        "type": "paragraph",
        "text": "hold `shift` to move snapped y by baseline rows. on unsnapped axes, `shift` increases the fine step."
      }
    ]
  },
  {
    "id": "tooltip-duplicate-layer",
    "title": "duplicate without losing rhythm",
    "blocks": [
      {
        "type": "paragraph",
        "text": "use the visible `+` control for duplication and transfer."
      },
      {
        "type": "paragraph",
        "text": "for text, `+` duplicates the paragraph. `shift` copies paragraph settings, `alt/option` copies typography, and `alt/option` + `shift` copies both. image placeholders duplicate directly."
      }
    ]
  },
  {
    "id": "tooltip-free-placement",
    "title": "free placement is an exception",
    "blocks": [
      {
        "type": "paragraph",
        "text": "turn off column or baseline snap only for a controlled optical exception."
      },
      {
        "type": "paragraph",
        "text": "free x placement can create a disciplined side-margin overhang. it is not for casual drift."
      }
    ]
  },
  {
    "id": "tooltip-smart-text-zoom",
    "title": "paragraph zoom keeps work local",
    "blocks": [
      {
        "type": "paragraph",
        "text": "keep paragraph zoom on for text-heavy pages."
      },
      {
        "type": "paragraph",
        "text": "entering text edit focuses the active paragraph. text and style edits keep the view stable. frame changes refit the paragraph."
      }
    ]
  },
  {
    "id": "tooltip-turbo-edit",
    "title": "retarget paragraph to paragraph",
    "blocks": [
      {
        "type": "paragraph",
        "text": "with an editor open, select another unlocked preview paragraph to retarget immediately."
      },
      {
        "type": "paragraph",
        "text": "use this to move through a page without repeatedly closing the editor."
      }
    ]
  },
  {
    "id": "tooltip-layer-card-retarget",
    "title": "retarget from layer cards",
    "blocks": [
      {
        "type": "paragraph",
        "text": "double-click an unlocked layer card in the project panel to open or retarget its editor."
      },
      {
        "type": "paragraph",
        "text": "single-click still selects the layer for nudging and ordering."
      }
    ]
  },
  {
    "id": "tooltip-rendered-text-editing",
    "title": "edit the rendered text",
    "blocks": [
      {
        "type": "paragraph",
        "text": "inline editing follows the rendered line layout."
      },
      {
        "type": "paragraph",
        "text": "double-click selects a word, triple-click selects a sentence, and `alt+a` or `cmd/ctrl+a` selects the paragraph."
      }
    ]
  },
  {
    "id": "tooltip-placeholder-editing",
    "title": "keep tokens visible while editing",
    "blocks": [
      {
        "type": "paragraph",
        "text": "document variables stay visible as raw tokens while editing and render as live values outside edit mode."
      },
      {
        "type": "paragraph",
        "text": "use them for folios, project titles, dates, times, and proof text with predictable control."
      }
    ]
  },
  {
    "id": "tooltip-rows-plus-baselines",
    "title": "height is rows plus baselines",
    "blocks": [
      {
        "type": "paragraph",
        "text": "paragraph and image heights are built from `rows + baselines`."
      },
      {
        "type": "paragraph",
        "text": "use full rows for modular blocks and baseline-only height for captions, folios, and shallow editorial frames."
      }
    ]
  },
  {
    "id": "tooltip-columns-before-reflow",
    "title": "set columns before reflow",
    "blocks": [
      {
        "type": "paragraph",
        "text": "choose `cols` before judging paragraph flow."
      },
      {
        "type": "paragraph",
        "text": "a weak line length is usually a measure problem. reflow and hyphenation work best after the measure is correct."
      }
    ]
  },
  {
    "id": "tooltip-frame-alignment",
    "title": "align inside the frame",
    "blocks": [
      {
        "type": "paragraph",
        "text": "alignment positions text inside the configured frame."
      },
      {
        "type": "paragraph",
        "text": "use it as a compositional decision within a clear frame, not as a repair."
      }
    ]
  },
  {
    "id": "tooltip-custom-type",
    "title": "use custom type sparingly",
    "blocks": [
      {
        "type": "paragraph",
        "text": "when first selected, `custom` copies the paragraph's resolved size and leading."
      },
      {
        "type": "paragraph",
        "text": "treat custom type as a local editorial exception after the hierarchy is clear."
      }
    ]
  },
  {
    "id": "tooltip-select-before-nudge",
    "title": "select before nudging",
    "blocks": [
      {
        "type": "paragraph",
        "text": "single-click a layer card to select it, then use arrow keys to nudge."
      },
      {
        "type": "paragraph",
        "text": "this keeps positional edits precise and avoids entering edit mode by accident."
      }
    ]
  },
  {
    "id": "tooltip-lock-finished-layers",
    "title": "lock resolved layers",
    "blocks": [
      {
        "type": "paragraph",
        "text": "lock layers once their position and role are resolved."
      },
      {
        "type": "paragraph",
        "text": "locked layers still show rollover guides, but cannot be moved, edited, duplicated, deleted, or retargeted until unlocked."
      }
    ]
  },
  {
    "id": "tooltip-page-cards",
    "title": "use page rows for document rhythm",
    "blocks": [
      {
        "type": "paragraph",
        "text": "use the `page` header or list icon to return from a layer stack to the page list."
      },
      {
        "type": "paragraph",
        "text": "page order is part of the design. treat it with the same discipline as modular field and hierarchy."
      }
    ]
  },
  {
    "id": "tooltip-facing-pages",
    "title": "use facing pages only for spreads",
    "blocks": [
      {
        "type": "paragraph",
        "text": "use `facing pages` only when two physical pages need one continuous editorial field."
      },
      {
        "type": "paragraph",
        "text": "a facing spread doubles the column field, mirrors inner and outer margins, and affects physical page variables."
      }
    ]
  },
  {
    "id": "tooltip-preview-guides",
    "title": "toggle guides while judging",
    "blocks": [
      {
        "type": "paragraph",
        "text": "use the header toggles to inspect baselines, margins, modules, typography, and image placeholders."
      },
      {
        "type": "paragraph",
        "text": "judge the same layout with and without construction lines. the rhythm should remain visible after the guides disappear."
      }
    ]
  },
  {
    "id": "tooltip-rollover-guides",
    "title": "rollover guides show the frame",
    "blocks": [
      {
        "type": "paragraph",
        "text": "hover a layer to see its edit access and placement guides."
      },
      {
        "type": "paragraph",
        "text": "paragraph guides follow the configured `rows + baselines` frame, not only the visible text bounds."
      }
    ]
  },
  {
    "id": "tooltip-help-hover",
    "title": "help hover is contextual",
    "blocks": [
      {
        "type": "paragraph",
        "text": "open help and hover marked areas for the matching reference."
      }
    ]
  },
  {
    "id": "tooltip-export-readiness",
    "title": "export after the system is stable",
    "blocks": [
      {
        "type": "paragraph",
        "text": "export should confirm a resolved layout, not repair it."
      },
      {
        "type": "paragraph",
        "text": "check page order, page range, visible guide toggles, rotation, page numbering, and document variables before export."
      }
    ]
  },
  {
    "id": "tooltip-export-format",
    "title": "choose export by downstream use",
    "blocks": [
      {
        "type": "paragraph",
        "text": "use `JSON` for editable project exchange, `PDF` for faithful vector output, `SVG` for frozen per-page geometry, and `IDML` for InDesign continuation."
      },
      {
        "type": "paragraph",
        "text": "the normal vector path freezes typography as planned geometry for `PDF`, `SVG`, and `IDML`."
      }
    ]
  },
  {
    "id": "tooltip-export-bleed",
    "title": "shared vector bleed",
    "blocks": [
      {
        "type": "paragraph",
        "text": "bleed applies to `PDF`, `SVG`, and `IDML` from one shared control."
      },
      {
        "type": "paragraph",
        "text": "it changes the export box and crop marks, not the page layout math."
      }
    ]
  },
  {
    "id": "tooltip-export-visibility",
    "title": "visible overlays are exported",
    "blocks": [
      {
        "type": "paragraph",
        "text": "export follows current guide visibility."
      },
      {
        "type": "paragraph",
        "text": "turn off construction guides before final output unless they are part of the deliverable."
      }
    ]
  },
  {
    "id": "tooltip-export-progress",
    "title": "export progress",
    "blocks": [
      {
        "type": "paragraph",
        "text": "progress is informational. export continues from the committed page plan."
      }
    ]
  },
  {
    "id": "tooltip-fix-loose-page",
    "title": "if the page feels loose",
    "blocks": [
      {
        "type": "paragraph",
        "text": "return to baseline, margins, and grid rhythm before editing individual paragraphs."
      },
      {
        "type": "paragraph",
        "text": "loose layouts usually need a clearer field, not more local styling."
      }
    ]
  },
  {
    "id": "tooltip-fix-weak-type",
    "title": "if text feels weak",
    "blocks": [
      {
        "type": "paragraph",
        "text": "check hierarchy, measure, leading, and baseline alignment before changing tracking."
      },
      {
        "type": "paragraph",
        "text": "tracking changes paragraph color. it refines texture; it does not replace hierarchy."
      }
    ]
  },
  {
    "id": "tooltip-grid-reduction",
    "title": "if content falls out of bounds",
    "blocks": [
      {
        "type": "paragraph",
        "text": "grid reductions are blocked when existing layers would fall outside the new field."
      },
      {
        "type": "paragraph",
        "text": "resolve layer placement first, then reduce rows or columns."
      }
    ]
  },
  {
    "id": "tooltip-faster-editing",
    "title": "if editing feels slow",
    "blocks": [
      {
        "type": "paragraph",
        "text": "use paragraph zoom, keep one editor open, and retarget from paragraph to paragraph."
      },
      {
        "type": "paragraph",
        "text": "the most efficient workflow is staying in context while moving deliberately through the page."
      }
    ]
  }
] as const satisfies readonly LayoutOpenTooltipItem[]
