/* eslint-disable */
// This file is generated by webapp/scripts/generate-tooltip-content.mjs from webapp/messages/en/content/tooltips.md.
// Do not edit this file directly.

export type TooltipBlock =
  | { type: "paragraph"; text: string }
  | { type: "list"; items: string[] }

export type LayoutOpenTooltipItem = {
  id: string
  title: string
  blocks: TooltipBlock[]
}

export const LAYOUT_OPEN_TOOLTIP_ITEMS = [
  {
    "id": "tooltip-start-with-system",
    "title": "Start with the page system",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Set canvas, baseline, margins, modular field, rhythm, type scale, and base family before placing many layers."
      },
      {
        "type": "paragraph",
        "text": "If the page feels unresolved, adjust the system first. Local paragraph changes are useful only after the field is stable."
      }
    ]
  },
  {
    "id": "tooltip-structure-before-styling",
    "title": "Structure before styling",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use `rows`, `baselines`, and `cols` to define the text frame before refining wording, tracking, or color."
      },
      {
        "type": "paragraph",
        "text": "The frame is the editorial decision. Styling should clarify it, not compensate for it."
      }
    ]
  },
  {
    "id": "tooltip-repetitive-reference",
    "title": "Use repetitive as a control",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Judge the page first in `repetitive` rhythm. It gives the clearest reading of margins, baseline, hierarchy, and measure."
      },
      {
        "type": "paragraph",
        "text": "Use Fibonacci, golden ratio, perfect fourth, or perfect fifth only when asymmetry strengthens the field."
      }
    ]
  },
  {
    "id": "tooltip-create-text",
    "title": "Create text on the grid",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Double-click inside a module to create a paragraph where the structure suggests it belongs."
      },
      {
        "type": "paragraph",
        "text": "The block starts on the clicked module, with hyphenation off, and clamps to the available columns."
      }
    ]
  },
  {
    "id": "tooltip-create-hierarchy",
    "title": "Choose hierarchy while creating",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Hold `1..5` while double-clicking to assign hierarchy immediately."
      },
      {
        "type": "paragraph",
        "text": "`1` caption, `2` body, `3` subhead, `4` headline, `5` display. The initial measure follows the role and the remaining column field."
      }
    ]
  },
  {
    "id": "tooltip-create-image",
    "title": "Place image placeholders deliberately",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use `Shift` + double-click on an empty module to create an image placeholder."
      },
      {
        "type": "paragraph",
        "text": "Placeholders share the same snap, span, baseline height, and rotation discipline as text."
      }
    ]
  },
  {
    "id": "tooltip-lorem-frame-test",
    "title": "Use lorem as a frame test",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Insert `<%lorem%>` to test whether a paragraph frame can carry the intended density."
      },
      {
        "type": "paragraph",
        "text": "The token fills the active frame using current rows, baselines, columns, reflow, and hyphenation."
      }
    ]
  },
  {
    "id": "tooltip-drag-and-nudge",
    "title": "Drag for placement, nudge for decision",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Drag to establish position. Use cursor keys for final placement."
      },
      {
        "type": "paragraph",
        "text": "Nudging follows the same logical grid model as dragging, so movement stays tied to the page system."
      }
    ]
  },
  {
    "id": "tooltip-cursor-nudge",
    "title": "Nudge with the grid",
    "blocks": [
      {
        "type": "paragraph",
        "text": "With snapped axes enabled, arrow keys move the selected unlocked layer by columns and module rows."
      },
      {
        "type": "paragraph",
        "text": "Hold `Shift` to move snapped y by baseline rows. On unsnapped axes, `Shift` increases the fine step."
      }
    ]
  },
  {
    "id": "tooltip-duplicate-layer",
    "title": "Duplicate without losing rhythm",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use the visible `+` control for duplication and transfer."
      },
      {
        "type": "paragraph",
        "text": "For text, `+` duplicates the paragraph. `Shift` copies paragraph settings, `Alt/Option` copies typography, and `Alt/Option` + `Shift` copies both. Image placeholders duplicate directly."
      }
    ]
  },
  {
    "id": "tooltip-free-placement",
    "title": "Free placement is an exception",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Turn off column or baseline snap only for a controlled optical exception."
      },
      {
        "type": "paragraph",
        "text": "Free x placement can create a disciplined side-margin overhang. It is not for casual drift."
      }
    ]
  },
  {
    "id": "tooltip-smart-text-zoom",
    "title": "Paragraph zoom keeps work local",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Keep paragraph zoom on for text-heavy pages."
      },
      {
        "type": "paragraph",
        "text": "Entering text edit focuses the active paragraph. Text and style edits keep the view stable. Frame changes refit the paragraph."
      }
    ]
  },
  {
    "id": "tooltip-turbo-edit",
    "title": "Retarget paragraph to paragraph",
    "blocks": [
      {
        "type": "paragraph",
        "text": "With an editor open, select another unlocked preview paragraph to retarget immediately."
      },
      {
        "type": "paragraph",
        "text": "Use this to move through a page without repeatedly closing the editor."
      }
    ]
  },
  {
    "id": "tooltip-layer-card-retarget",
    "title": "Retarget from layer cards",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Double-click an unlocked layer card in the project panel to open or retarget its editor."
      },
      {
        "type": "paragraph",
        "text": "Single-click still selects the layer for nudging and ordering."
      }
    ]
  },
  {
    "id": "tooltip-rendered-text-editing",
    "title": "Edit the rendered text",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Inline editing follows the rendered line layout."
      },
      {
        "type": "paragraph",
        "text": "Double-click selects a word, triple-click selects a sentence, and `alt+a` or `Cmd/Ctrl+A` selects the paragraph."
      }
    ]
  },
  {
    "id": "tooltip-placeholder-editing",
    "title": "Keep tokens visible while editing",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Document variables stay visible as raw tokens while editing and render as live values outside edit mode."
      },
      {
        "type": "paragraph",
        "text": "Use them for folios, project titles, dates, times, and proof text with predictable control."
      }
    ]
  },
  {
    "id": "tooltip-rows-plus-baselines",
    "title": "Height is rows plus baselines",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Paragraph and image heights are built from `rows + baselines`."
      },
      {
        "type": "paragraph",
        "text": "Use full rows for modular blocks and baseline-only height for captions, folios, and shallow editorial frames."
      }
    ]
  },
  {
    "id": "tooltip-columns-before-reflow",
    "title": "Set columns before reflow",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Choose `cols` before judging paragraph flow."
      },
      {
        "type": "paragraph",
        "text": "A weak line length is usually a measure problem. Reflow and hyphenation work best after the measure is correct."
      }
    ]
  },
  {
    "id": "tooltip-frame-alignment",
    "title": "Align inside the frame",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Alignment positions text inside the configured frame."
      },
      {
        "type": "paragraph",
        "text": "Use it as a compositional decision within a clear frame, not as a repair."
      }
    ]
  },
  {
    "id": "tooltip-custom-type",
    "title": "Use custom type sparingly",
    "blocks": [
      {
        "type": "paragraph",
        "text": "When first selected, `custom` copies the paragraph's resolved size and leading."
      },
      {
        "type": "paragraph",
        "text": "Treat custom type as a local editorial exception after the hierarchy is clear."
      }
    ]
  },
  {
    "id": "tooltip-select-before-nudge",
    "title": "Select before nudging",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Single-click a layer card to select it, then use arrow keys to nudge."
      },
      {
        "type": "paragraph",
        "text": "This keeps positional edits precise and avoids entering edit mode by accident."
      }
    ]
  },
  {
    "id": "tooltip-lock-finished-layers",
    "title": "Lock resolved layers",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Lock layers once their position and role are resolved."
      },
      {
        "type": "paragraph",
        "text": "Locked layers still show rollover guides, but cannot be moved, edited, duplicated, deleted, or retargeted until unlocked."
      }
    ]
  },
  {
    "id": "tooltip-page-cards",
    "title": "Use page rows for document rhythm",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use the `page` header or list icon to return from a layer stack to the page list."
      },
      {
        "type": "paragraph",
        "text": "Page order is part of the design. Treat it with the same discipline as modular field and hierarchy."
      }
    ]
  },
  {
    "id": "tooltip-facing-pages",
    "title": "Use facing pages only for spreads",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use `facing pages` only when two physical pages need one continuous editorial field."
      },
      {
        "type": "paragraph",
        "text": "A facing spread doubles the column field, mirrors inner and outer margins, and affects physical page variables."
      }
    ]
  },
  {
    "id": "tooltip-preview-guides",
    "title": "Toggle guides while judging",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use the header toggles to inspect baselines, margins, modules, typography, and image placeholders."
      },
      {
        "type": "paragraph",
        "text": "Judge the same layout with and without construction lines. The rhythm should remain visible after the guides disappear."
      }
    ]
  },
  {
    "id": "tooltip-rollover-guides",
    "title": "Rollover guides show the frame",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Hover a layer to see its edit access and placement guides."
      },
      {
        "type": "paragraph",
        "text": "Paragraph guides follow the configured `rows + baselines` frame, not only the visible text bounds."
      }
    ]
  },
  {
    "id": "tooltip-help-hover",
    "title": "Help hover is contextual",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Open help and hover marked areas for the matching reference."
      }
    ]
  },
  {
    "id": "tooltip-export-readiness",
    "title": "Export after the system is stable",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Export should confirm a resolved layout, not repair it."
      },
      {
        "type": "paragraph",
        "text": "Check page order, page range, visible guide toggles, rotation, page numbering, and document variables before export."
      }
    ]
  },
  {
    "id": "tooltip-export-format",
    "title": "Choose export by downstream use",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use `JSON` for editable project exchange, `PDF` for faithful vector output, `SVG` for frozen per-page geometry, and `IDML` for InDesign continuation."
      },
      {
        "type": "paragraph",
        "text": "The normal vector path freezes typography as planned geometry for `PDF`, `SVG`, and `IDML`."
      }
    ]
  },
  {
    "id": "tooltip-export-bleed",
    "title": "Shared vector bleed",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Bleed applies to `PDF`, `SVG`, and `IDML` from one shared control."
      },
      {
        "type": "paragraph",
        "text": "It changes the export box and crop marks, not the page layout math."
      }
    ]
  },
  {
    "id": "tooltip-export-visibility",
    "title": "Visible overlays are exported",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Export follows current guide visibility."
      },
      {
        "type": "paragraph",
        "text": "Turn off construction guides before final output unless they are part of the deliverable."
      }
    ]
  },
  {
    "id": "tooltip-export-progress",
    "title": "Export progress",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Progress is informational. Export continues from the committed page plan."
      }
    ]
  },
  {
    "id": "tooltip-fix-loose-page",
    "title": "If the page feels loose",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Return to baseline, margins, and grid rhythm before editing individual paragraphs."
      },
      {
        "type": "paragraph",
        "text": "Loose layouts usually need a clearer field, not more local styling."
      }
    ]
  },
  {
    "id": "tooltip-fix-weak-type",
    "title": "If text feels weak",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Check hierarchy, measure, leading, and baseline alignment before changing tracking."
      },
      {
        "type": "paragraph",
        "text": "Tracking changes paragraph color. It refines texture; it does not replace hierarchy."
      }
    ]
  },
  {
    "id": "tooltip-grid-reduction",
    "title": "If content falls out of bounds",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Grid reductions are blocked when existing layers would fall outside the new field."
      },
      {
        "type": "paragraph",
        "text": "Resolve layer placement first, then reduce rows or columns."
      }
    ]
  },
  {
    "id": "tooltip-faster-editing",
    "title": "If editing feels slow",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use paragraph zoom, keep one editor open, and retarget from paragraph to paragraph."
      },
      {
        "type": "paragraph",
        "text": "The most efficient workflow is staying in context while moving deliberately through the page."
      }
    ]
  }
] as const satisfies readonly LayoutOpenTooltipItem[]
