/* eslint-disable */
// This file is generated by webapp/scripts/generate-tooltip-content.mjs from DOCUMENTATION.md.
// Do not edit this file directly.

export type TooltipBlock =
  | { type: "paragraph"; text: string }
  | { type: "list"; items: string[] }

export type DocumentationHoverInfoItem = {
  id: string
  title: string
  blocks: TooltipBlock[]
}

export type LayoutOpenTooltipItem = DocumentationHoverInfoItem

export const DOCUMENTATION_HOVER_INFO_ITEMS = [
  {
    "id": "tooltip-start-with-system",
    "title": "Start with the page system",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Set canvas, baseline, margins, modular field, rhythm, type scale, and base family before placing many layers."
      },
      {
        "type": "paragraph",
        "text": "If the page feels unresolved, adjust the system first. Local paragraph changes are useful only after the field is stable."
      }
    ]
  },
  {
    "id": "tooltip-structure-before-styling",
    "title": "Structure before styling",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use `rows`, `baselines`, and `cols` to define the text frame before refining wording, tracking, or color."
      },
      {
        "type": "paragraph",
        "text": "The frame is the editorial decision. Styling should clarify it, not compensate for it."
      }
    ]
  },
  {
    "id": "tooltip-repetitive-reference",
    "title": "Use repetitive as a control",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Judge the page first in `repetitive` rhythm. It gives the clearest reading of margins, baseline, hierarchy, and measure."
      },
      {
        "type": "paragraph",
        "text": "Use Fibonacci, golden ratio, perfect fourth, or perfect fifth only when asymmetry strengthens the field."
      }
    ]
  },
  {
    "id": "tooltip-create-text",
    "title": "Create text on the grid",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Double-click inside a module to create a paragraph where the structure suggests it belongs."
      },
      {
        "type": "paragraph",
        "text": "The block starts on the clicked module, with hyphenation off, and clamps to the available columns."
      }
    ]
  },
  {
    "id": "tooltip-create-hierarchy",
    "title": "Choose hierarchy while creating",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Hold `1..5` while double-clicking to assign hierarchy immediately."
      },
      {
        "type": "paragraph",
        "text": "`1` caption, `2` body, `3` subhead, `4` headline, `5` display. The initial measure follows the role and the remaining column field."
      }
    ]
  },
  {
    "id": "tooltip-create-image",
    "title": "Place image placeholders deliberately",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use `Shift` + double-click on an empty module to create an image placeholder. Hold `1..4` with `Shift` to assign the active base-scheme swatch while creating it."
      },
      {
        "type": "paragraph",
        "text": "Placeholders share the same snap, span, baseline height, and rotation discipline as text."
      }
    ]
  },
  {
    "id": "tooltip-lorem-frame-test",
    "title": "Use lorem as a frame test",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Insert `<%lorem%>` to test whether a paragraph frame can carry the intended density."
      },
      {
        "type": "paragraph",
        "text": "The token fills the active frame using current rows, baselines, columns, reflow, and hyphenation."
      }
    ]
  },
  {
    "id": "tooltip-drag-and-nudge",
    "title": "Drag for placement, nudge for decision",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Drag to establish position. Use cursor keys for final placement."
      },
      {
        "type": "paragraph",
        "text": "Nudging follows the same logical grid model as dragging, so movement stays tied to the page system."
      }
    ]
  },
  {
    "id": "tooltip-cursor-nudge",
    "title": "Nudge with the grid",
    "blocks": [
      {
        "type": "paragraph",
        "text": "With snapped axes enabled, arrow keys move the selected unlocked layer by columns and module rows."
      },
      {
        "type": "paragraph",
        "text": "Hold `Shift` to move snapped y by baseline rows. On unsnapped axes, `Shift` increases the fine step."
      }
    ]
  },
  {
    "id": "tooltip-duplicate-layer",
    "title": "Duplicate without losing rhythm",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use the visible `+` control for duplication and transfer."
      },
      {
        "type": "paragraph",
        "text": "For text, `+` duplicates the paragraph. `Shift` copies paragraph settings, `Alt/Option` copies typography, and `Alt/Option` + `Shift` copies both. Image placeholders duplicate directly."
      }
    ]
  },
  {
    "id": "tooltip-free-placement",
    "title": "Free placement is an exception",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Turn off column or baseline snap only for a controlled optical exception."
      },
      {
        "type": "paragraph",
        "text": "Free x placement can create a disciplined side-margin overhang. It is not for casual drift."
      }
    ]
  },
  {
    "id": "tooltip-smart-text-zoom",
    "title": "Paragraph zoom keeps work local",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Keep paragraph zoom on for text-heavy pages."
      },
      {
        "type": "paragraph",
        "text": "Entering text edit focuses the active paragraph. Text and style edits keep the view stable. Frame changes refit the paragraph."
      }
    ]
  },
  {
    "id": "tooltip-turbo-edit",
    "title": "Retarget paragraph to paragraph",
    "blocks": [
      {
        "type": "paragraph",
        "text": "With an editor open, select another unlocked preview paragraph to retarget immediately."
      },
      {
        "type": "paragraph",
        "text": "Use this to move through a page without repeatedly closing the editor."
      }
    ]
  },
  {
    "id": "tooltip-layer-card-retarget",
    "title": "Retarget from layer cards",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Double-click an unlocked layer card in the project panel to open or retarget its editor."
      },
      {
        "type": "paragraph",
        "text": "Single-click still selects the layer for nudging and ordering."
      }
    ]
  },
  {
    "id": "tooltip-rendered-text-editing",
    "title": "Edit the rendered text",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Inline editing follows the rendered line layout."
      },
      {
        "type": "paragraph",
        "text": "Double-click selects a word, triple-click selects a sentence, and `alt+a` or `Cmd/Ctrl+A` selects the paragraph."
      }
    ]
  },
  {
    "id": "tooltip-placeholder-editing",
    "title": "Keep tokens visible while editing",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Document variables stay visible as raw tokens while editing and render as live values outside edit mode."
      },
      {
        "type": "paragraph",
        "text": "Use them for folios, project titles, dates, times, and proof text with predictable control."
      }
    ]
  },
  {
    "id": "tooltip-rows-plus-baselines",
    "title": "Height is rows plus baselines",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Paragraph and image heights are built from `rows + baselines`."
      },
      {
        "type": "paragraph",
        "text": "Use full rows for modular blocks and baseline-only height for captions, folios, and shallow editorial frames."
      }
    ]
  },
  {
    "id": "tooltip-columns-before-reflow",
    "title": "Set columns before reflow",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Choose `cols` before judging paragraph flow."
      },
      {
        "type": "paragraph",
        "text": "A weak line length is usually a measure problem. Reflow and hyphenation work best after the measure is correct."
      }
    ]
  },
  {
    "id": "tooltip-frame-alignment",
    "title": "Align inside the frame",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Alignment positions text inside the configured frame."
      },
      {
        "type": "paragraph",
        "text": "Use it as a compositional decision within a clear frame, not as a repair."
      }
    ]
  },
  {
    "id": "tooltip-custom-type",
    "title": "Use custom type sparingly",
    "blocks": [
      {
        "type": "paragraph",
        "text": "When first selected, `custom` copies the paragraph's resolved size and leading."
      },
      {
        "type": "paragraph",
        "text": "Treat custom type as a local editorial exception after the hierarchy is clear."
      }
    ]
  },
  {
    "id": "tooltip-select-before-nudge",
    "title": "Select before nudging",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Single-click a layer card to select it, then use arrow keys to nudge."
      },
      {
        "type": "paragraph",
        "text": "This keeps positional edits precise and avoids entering edit mode by accident."
      }
    ]
  },
  {
    "id": "tooltip-lock-finished-layers",
    "title": "Lock resolved layers",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Lock layers once their position and role are resolved."
      },
      {
        "type": "paragraph",
        "text": "Locked layers still show rollover guides, but cannot be moved, edited, duplicated, deleted, or retargeted until unlocked."
      }
    ]
  },
  {
    "id": "tooltip-page-cards",
    "title": "Use page rows for document rhythm",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use the `page` header or list icon to return from a layer stack to the page list."
      },
      {
        "type": "paragraph",
        "text": "Page order is part of the design. Treat it with the same discipline as modular field and hierarchy."
      }
    ]
  },
  {
    "id": "tooltip-facing-pages",
    "title": "Use facing pages only for spreads",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use `facing pages` only when two physical pages need one continuous editorial field."
      },
      {
        "type": "paragraph",
        "text": "A facing spread doubles the column field, mirrors inner and outer margins, and affects physical page variables."
      }
    ]
  },
  {
    "id": "tooltip-preview-guides",
    "title": "Toggle guides while judging",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use the header toggles to inspect baselines, margins, modules, typography, and image placeholders."
      },
      {
        "type": "paragraph",
        "text": "Judge the same layout with and without construction lines. The rhythm should remain visible after the guides disappear."
      }
    ]
  },
  {
    "id": "tooltip-rollover-guides",
    "title": "Rollover guides show the frame",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Hover a layer to see its edit access and placement guides."
      },
      {
        "type": "paragraph",
        "text": "Paragraph guides follow the configured `rows + baselines` frame, not only the visible text bounds."
      }
    ]
  },
  {
    "id": "tooltip-documentation-link",
    "title": "Documentation stays external",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use the documentation link for the full reference. Keep the canvas focused on the layout."
      }
    ]
  },
  {
    "id": "tooltip-export-readiness",
    "title": "Export after the system is stable",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Export should confirm a resolved layout, not repair it."
      },
      {
        "type": "paragraph",
        "text": "Check page order, page range, visible guide toggles, rotation, page numbering, and document variables before export."
      }
    ]
  },
  {
    "id": "tooltip-export-format",
    "title": "Choose export by downstream use",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use `JSON` for editable project exchange, `PDF` for faithful vector output, `SVG` for frozen per-page geometry, and `IDML` for InDesign continuation."
      },
      {
        "type": "paragraph",
        "text": "The normal vector path freezes typography as planned geometry for `PDF`, `SVG`, and `IDML`."
      }
    ]
  },
  {
    "id": "tooltip-export-bleed",
    "title": "Shared vector bleed",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Bleed applies to `PDF`, `SVG`, and `IDML` from one shared control."
      },
      {
        "type": "paragraph",
        "text": "It changes the export box and crop marks, not the page layout math."
      }
    ]
  },
  {
    "id": "tooltip-export-visibility",
    "title": "Visible overlays are exported",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Export follows current guide visibility."
      },
      {
        "type": "paragraph",
        "text": "Turn off construction guides before final output unless they are part of the deliverable."
      }
    ]
  },
  {
    "id": "tooltip-export-progress",
    "title": "Export progress",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Progress is informational. Export continues from the committed page plan."
      }
    ]
  },
  {
    "id": "tooltip-fix-loose-page",
    "title": "If the page feels loose",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Return to baseline, margins, and grid rhythm before editing individual paragraphs."
      },
      {
        "type": "paragraph",
        "text": "Loose layouts usually need a clearer field, not more local styling."
      }
    ]
  },
  {
    "id": "tooltip-fix-weak-type",
    "title": "If text feels weak",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Check hierarchy, measure, leading, and baseline alignment before changing tracking."
      },
      {
        "type": "paragraph",
        "text": "Tracking changes paragraph color. It refines texture; it does not replace hierarchy."
      }
    ]
  },
  {
    "id": "tooltip-grid-reduction",
    "title": "If content falls out of bounds",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Grid reductions are blocked when existing layers would fall outside the new field."
      },
      {
        "type": "paragraph",
        "text": "Resolve layer placement first, then reduce rows or columns."
      }
    ]
  },
  {
    "id": "tooltip-faster-editing",
    "title": "If editing feels slow",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use paragraph zoom, keep one editor open, and retarget from paragraph to paragraph."
      },
      {
        "type": "paragraph",
        "text": "The most efficient workflow is staying in context while moving deliberately through the page."
      }
    ]
  },
  {
    "id": "tooltip-header-presets",
    "title": "Preset browser",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Opens the preset browser. Presets replace the active project state, so review the thumbnail and metadata before loading a different system."
      }
    ]
  },
  {
    "id": "tooltip-header-import",
    "title": "Import project",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Loads a saved Swiss Grid Generator project file. The imported project becomes the active document and should be checked against the preview before export."
      }
    ]
  },
  {
    "id": "tooltip-header-save",
    "title": "Save to library",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Stores the current document in the local library. The status dot reports whether the document can be stored and whether the library copy needs attention."
      }
    ]
  },
  {
    "id": "tooltip-header-export",
    "title": "Export dialog",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Opens export preparation. Use it after the layout, guides, visibility, metadata, and page range have been checked."
      }
    ]
  },
  {
    "id": "tooltip-header-history",
    "title": "History actions",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Undo and redo restore authored document states. They are intentionally disabled when no matching state exists."
      }
    ]
  },
  {
    "id": "tooltip-header-guide-visibility",
    "title": "Guide visibility",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Toggles the preview guide layers. These controls affect the editing surface and export options, but they do not change the planned grid geometry."
      }
    ]
  },
  {
    "id": "tooltip-header-project-panel",
    "title": "Project panel",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Shows the page and layer panels. Use it to inspect page order, facing-page state, and the active layer list."
      }
    ]
  },
  {
    "id": "tooltip-header-account",
    "title": "Account panel",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Shows account and cloud status. The status dot reports whether library sync is connected, pending, or blocked."
      }
    ]
  },
  {
    "id": "tooltip-header-support-menu",
    "title": "Support menu",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Collects secondary workspace actions: hover info, display mode, clipboard layout transfer, documentation, feedback, and legal text."
      }
    ]
  },
  {
    "id": "tooltip-settings-canvas",
    "title": "Canvas settings",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Defines the document format, ratio, orientation, and rotation. These values set the page box consumed by preview and export."
      }
    ]
  },
  {
    "id": "tooltip-settings-baseline",
    "title": "Baseline settings",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Defines the baseline unit for the system. Text rhythm, rows, and many snap decisions depend on this value."
      }
    ]
  },
  {
    "id": "tooltip-settings-margins",
    "title": "Margin settings",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Defines the active page frame. Margin method changes affect the available composition area before layers are placed."
      }
    ]
  },
  {
    "id": "tooltip-settings-grid",
    "title": "Grid settings",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Defines rows, columns, gutters, and rhythm. The grid is structural; layer placement and export geometry consume the resulting plan."
      }
    ]
  },
  {
    "id": "tooltip-settings-typography",
    "title": "Typography settings",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Defines the global typographic scale and base family. Paragraph defaults inherit from these values unless a selected layer overrides them."
      }
    ]
  },
  {
    "id": "tooltip-settings-color",
    "title": "Color settings",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Defines the page ground and active palette. Color choices affect preview, exported graphics, and editor swatches."
      }
    ]
  },
  {
    "id": "tooltip-control-custom-ratio",
    "title": "Custom ratio fields",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Sets the numeric width-to-height ratio for custom formats. The ratio is normalized before the page box is planned."
      }
    ]
  },
  {
    "id": "tooltip-control-rotation",
    "title": "Rotation control",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Rotates the selected page or layer in planned coordinates. The value is rounded to the control step before preview and export consume it."
      }
    ]
  },
  {
    "id": "tooltip-control-margin-method",
    "title": "Margin method control",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Switches the margin construction method. Preview highlights the candidate method before it is committed."
      }
    ]
  },
  {
    "id": "tooltip-control-grid-size",
    "title": "Grid size controls",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Changes the structural row and column count. Existing layers keep their authored coordinates and may need review after large grid changes."
      }
    ]
  },
  {
    "id": "tooltip-control-grid-rhythm",
    "title": "Grid rhythm controls",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Changes how rows and columns expand across the page. Rhythm choices are calculated before layer placement."
      }
    ]
  },
  {
    "id": "tooltip-control-type-rhythm",
    "title": "Type rhythm controls",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Changes the global type scale. Paragraphs that use style presets follow this rhythm; custom sizes remain explicit."
      }
    ]
  },
  {
    "id": "tooltip-control-base-family",
    "title": "Base family control",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Changes the document base font family. Export resolves available cuts from this family before drawing text."
      }
    ]
  },
  {
    "id": "tooltip-control-page-ground",
    "title": "Page ground control",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Changes the page background color. This is part of the document appearance and is included in exported formats when enabled."
      }
    ]
  },
  {
    "id": "tooltip-editor-paragraph",
    "title": "Paragraph geometry",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Edits the selected paragraph frame: rows, columns, baselines, alignment, rotation, reflow, and snap behavior. The frame is the first hit area for hover and selection."
      }
    ]
  },
  {
    "id": "tooltip-editor-typography",
    "title": "Paragraph typography",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Edits the selected paragraph type settings. Style, family, cut, kerning, tracking, and color are written back to the layer."
      }
    ]
  },
  {
    "id": "tooltip-editor-symbols",
    "title": "Symbol insertion",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Inserts typographic symbols into the active text editor. Symbols are inserted as text and remain part of the paragraph content."
      }
    ]
  },
  {
    "id": "tooltip-editor-placeholders",
    "title": "Placeholder insertion",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Inserts document variables such as page number and project title. Placeholders resolve from the active project context during preview and export."
      }
    ]
  },
  {
    "id": "tooltip-editor-info",
    "title": "Paragraph information",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Reports the current paragraph metadata. Use it to check character count, word count, and selected layer state."
      }
    ]
  },
  {
    "id": "tooltip-editor-image-geometry",
    "title": "Image geometry",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Edits the selected image frame. Rows, columns, baselines, rotation, and snap values determine the exported image box."
      }
    ]
  },
  {
    "id": "tooltip-editor-image-color",
    "title": "Image color",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Edits image placeholder color and transparency. These values affect the visual placeholder in preview and export."
      }
    ]
  },
  {
    "id": "tooltip-editor-image-info",
    "title": "Image information",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Reports the selected image layer metadata. Use it to check geometry, color, and opacity before export."
      }
    ]
  },
  {
    "id": "tooltip-control-snap-x",
    "title": "Column snap control",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Locks horizontal layer movement to the column grid. Disable it only when free placement is needed."
      }
    ]
  },
  {
    "id": "tooltip-control-snap-y",
    "title": "Baseline snap control",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Locks vertical layer movement to the baseline grid. This keeps text and image frames aligned to the typographic system."
      }
    ]
  },
  {
    "id": "tooltip-control-reflow",
    "title": "Reflow control",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Allows a paragraph to continue across its assigned columns. Use it for newspaper-like columns; keep it off for isolated text blocks."
      }
    ]
  },
  {
    "id": "tooltip-control-hyphenation",
    "title": "Hyphenation control",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Allows syllable division inside the selected paragraph. It improves measure fit while preserving the planned frame."
      }
    ]
  },
  {
    "id": "tooltip-control-tracking",
    "title": "Tracking control",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Adjusts letter spacing for the selected paragraph. Use small values and verify line breaks after changing it."
      }
    ]
  },
  {
    "id": "tooltip-control-transparency",
    "title": "Transparency control",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Sets image placeholder opacity. Lower opacity can reveal grid structure while retaining the planned image area."
      }
    ]
  },
  {
    "id": "tooltip-preview-create",
    "title": "Create page control",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Adds a clean page or duplicates content with the modifier shortcut. Page creation updates project order and document variables."
      }
    ]
  },
  {
    "id": "tooltip-preview-layer-affordances",
    "title": "Preview layer affordances",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Hover affordances edit, duplicate, resize, lock, and delete the active preview layer. Paragraph backgrounds remain the primary hover target."
      }
    ]
  },
  {
    "id": "tooltip-project-pages",
    "title": "Page list",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Controls page order, names, and facing-page state. Page order drives page numbers, export order, and document variables."
      }
    ]
  },
  {
    "id": "tooltip-project-layer-cards",
    "title": "Layer cards",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Show the layers on the active page. Use them for selection, locking, deletion, and editor retargeting when the canvas is dense."
      }
    ]
  },
  {
    "id": "tooltip-project-metadata",
    "title": "Project metadata",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Shows project title, author, dates, document size, and typography statistics. Metadata supports review and library management."
      }
    ]
  },
  {
    "id": "tooltip-project-facing-pages",
    "title": "Facing pages control",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Pairs pages into spreads for preview and export review. Facing-page state changes the editing context, not the underlying page geometry."
      }
    ]
  },
  {
    "id": "tooltip-preset-browser",
    "title": "Preset cards",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Show stored and built-in systems with format, grid, margin, rhythm, and metadata. Loading a card replaces the active document."
      }
    ]
  },
  {
    "id": "tooltip-user-library",
    "title": "User library",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Stores local presets and reports cloud sync state when account sync is active. User presets can be opened, exported, copied, or deleted."
      }
    ]
  },
  {
    "id": "tooltip-export-dialog",
    "title": "Export surface",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Collects export format, guide visibility, metadata, and page range. Export consumes the same planned document used by preview."
      }
    ]
  },
  {
    "id": "tooltip-export-page-range",
    "title": "Export page range",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Limits output to a selected page interval. Review facing spreads and page numbering before exporting a partial range."
      }
    ]
  },
  {
    "id": "tooltip-export-metadata",
    "title": "Export metadata",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Embeds title, author, subject, and related document fields where the selected export format supports them."
      }
    ]
  },
  {
    "id": "tooltip-export-progress-log",
    "title": "Export progress log",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Reports export preparation and file generation. A failed step should be corrected in the document before another export run."
      }
    ]
  },
  {
    "id": "tooltip-account-cloud",
    "title": "Account and cloud",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Shows sign-in, sign-out, and sync state. Cloud actions affect library synchronization, not the open document geometry."
      }
    ]
  },
  {
    "id": "tooltip-feedback-panel",
    "title": "Feedback panel",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Collects feedback and optional screenshots for product review. It does not change the current document."
      }
    ]
  },
  {
    "id": "tooltip-legal-panel",
    "title": "Legal panel",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Shows license and legal information for the application. It is informational and does not affect project state."
      }
    ]
  }
] as const satisfies readonly DocumentationHoverInfoItem[]

export const DOCUMENTATION_HOVER_INFO_BY_ID = Object.fromEntries(
  DOCUMENTATION_HOVER_INFO_ITEMS.map((item) => [item.id, item]),
) as Record<(typeof DOCUMENTATION_HOVER_INFO_ITEMS)[number]["id"], (typeof DOCUMENTATION_HOVER_INFO_ITEMS)[number]>

export type DocumentationHoverInfoId = keyof typeof DOCUMENTATION_HOVER_INFO_BY_ID

export const LAYOUT_OPEN_TOOLTIP_IDS = [
  "tooltip-start-with-system",
  "tooltip-structure-before-styling",
  "tooltip-repetitive-reference",
  "tooltip-create-text",
  "tooltip-create-hierarchy",
  "tooltip-create-image",
  "tooltip-lorem-frame-test",
  "tooltip-drag-and-nudge",
  "tooltip-cursor-nudge",
  "tooltip-duplicate-layer",
  "tooltip-free-placement",
  "tooltip-smart-text-zoom",
  "tooltip-turbo-edit",
  "tooltip-layer-card-retarget",
  "tooltip-rendered-text-editing",
  "tooltip-placeholder-editing",
  "tooltip-rows-plus-baselines",
  "tooltip-columns-before-reflow",
  "tooltip-frame-alignment",
  "tooltip-custom-type",
  "tooltip-select-before-nudge",
  "tooltip-lock-finished-layers",
  "tooltip-page-cards",
  "tooltip-facing-pages",
  "tooltip-preview-guides",
  "tooltip-rollover-guides",
  "tooltip-documentation-link",
  "tooltip-export-readiness",
  "tooltip-export-format",
  "tooltip-export-bleed",
  "tooltip-export-visibility",
  "tooltip-export-progress",
  "tooltip-fix-loose-page",
  "tooltip-fix-weak-type",
  "tooltip-grid-reduction",
  "tooltip-faster-editing"
] as const

export const LAYOUT_OPEN_TOOLTIP_ITEMS = [
  {
    "id": "tooltip-start-with-system",
    "title": "Start with the page system",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Set canvas, baseline, margins, modular field, rhythm, type scale, and base family before placing many layers."
      },
      {
        "type": "paragraph",
        "text": "If the page feels unresolved, adjust the system first. Local paragraph changes are useful only after the field is stable."
      }
    ]
  },
  {
    "id": "tooltip-structure-before-styling",
    "title": "Structure before styling",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use `rows`, `baselines`, and `cols` to define the text frame before refining wording, tracking, or color."
      },
      {
        "type": "paragraph",
        "text": "The frame is the editorial decision. Styling should clarify it, not compensate for it."
      }
    ]
  },
  {
    "id": "tooltip-repetitive-reference",
    "title": "Use repetitive as a control",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Judge the page first in `repetitive` rhythm. It gives the clearest reading of margins, baseline, hierarchy, and measure."
      },
      {
        "type": "paragraph",
        "text": "Use Fibonacci, golden ratio, perfect fourth, or perfect fifth only when asymmetry strengthens the field."
      }
    ]
  },
  {
    "id": "tooltip-create-text",
    "title": "Create text on the grid",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Double-click inside a module to create a paragraph where the structure suggests it belongs."
      },
      {
        "type": "paragraph",
        "text": "The block starts on the clicked module, with hyphenation off, and clamps to the available columns."
      }
    ]
  },
  {
    "id": "tooltip-create-hierarchy",
    "title": "Choose hierarchy while creating",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Hold `1..5` while double-clicking to assign hierarchy immediately."
      },
      {
        "type": "paragraph",
        "text": "`1` caption, `2` body, `3` subhead, `4` headline, `5` display. The initial measure follows the role and the remaining column field."
      }
    ]
  },
  {
    "id": "tooltip-create-image",
    "title": "Place image placeholders deliberately",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use `Shift` + double-click on an empty module to create an image placeholder. Hold `1..4` with `Shift` to assign the active base-scheme swatch while creating it."
      },
      {
        "type": "paragraph",
        "text": "Placeholders share the same snap, span, baseline height, and rotation discipline as text."
      }
    ]
  },
  {
    "id": "tooltip-lorem-frame-test",
    "title": "Use lorem as a frame test",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Insert `<%lorem%>` to test whether a paragraph frame can carry the intended density."
      },
      {
        "type": "paragraph",
        "text": "The token fills the active frame using current rows, baselines, columns, reflow, and hyphenation."
      }
    ]
  },
  {
    "id": "tooltip-drag-and-nudge",
    "title": "Drag for placement, nudge for decision",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Drag to establish position. Use cursor keys for final placement."
      },
      {
        "type": "paragraph",
        "text": "Nudging follows the same logical grid model as dragging, so movement stays tied to the page system."
      }
    ]
  },
  {
    "id": "tooltip-cursor-nudge",
    "title": "Nudge with the grid",
    "blocks": [
      {
        "type": "paragraph",
        "text": "With snapped axes enabled, arrow keys move the selected unlocked layer by columns and module rows."
      },
      {
        "type": "paragraph",
        "text": "Hold `Shift` to move snapped y by baseline rows. On unsnapped axes, `Shift` increases the fine step."
      }
    ]
  },
  {
    "id": "tooltip-duplicate-layer",
    "title": "Duplicate without losing rhythm",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use the visible `+` control for duplication and transfer."
      },
      {
        "type": "paragraph",
        "text": "For text, `+` duplicates the paragraph. `Shift` copies paragraph settings, `Alt/Option` copies typography, and `Alt/Option` + `Shift` copies both. Image placeholders duplicate directly."
      }
    ]
  },
  {
    "id": "tooltip-free-placement",
    "title": "Free placement is an exception",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Turn off column or baseline snap only for a controlled optical exception."
      },
      {
        "type": "paragraph",
        "text": "Free x placement can create a disciplined side-margin overhang. It is not for casual drift."
      }
    ]
  },
  {
    "id": "tooltip-smart-text-zoom",
    "title": "Paragraph zoom keeps work local",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Keep paragraph zoom on for text-heavy pages."
      },
      {
        "type": "paragraph",
        "text": "Entering text edit focuses the active paragraph. Text and style edits keep the view stable. Frame changes refit the paragraph."
      }
    ]
  },
  {
    "id": "tooltip-turbo-edit",
    "title": "Retarget paragraph to paragraph",
    "blocks": [
      {
        "type": "paragraph",
        "text": "With an editor open, select another unlocked preview paragraph to retarget immediately."
      },
      {
        "type": "paragraph",
        "text": "Use this to move through a page without repeatedly closing the editor."
      }
    ]
  },
  {
    "id": "tooltip-layer-card-retarget",
    "title": "Retarget from layer cards",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Double-click an unlocked layer card in the project panel to open or retarget its editor."
      },
      {
        "type": "paragraph",
        "text": "Single-click still selects the layer for nudging and ordering."
      }
    ]
  },
  {
    "id": "tooltip-rendered-text-editing",
    "title": "Edit the rendered text",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Inline editing follows the rendered line layout."
      },
      {
        "type": "paragraph",
        "text": "Double-click selects a word, triple-click selects a sentence, and `alt+a` or `Cmd/Ctrl+A` selects the paragraph."
      }
    ]
  },
  {
    "id": "tooltip-placeholder-editing",
    "title": "Keep tokens visible while editing",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Document variables stay visible as raw tokens while editing and render as live values outside edit mode."
      },
      {
        "type": "paragraph",
        "text": "Use them for folios, project titles, dates, times, and proof text with predictable control."
      }
    ]
  },
  {
    "id": "tooltip-rows-plus-baselines",
    "title": "Height is rows plus baselines",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Paragraph and image heights are built from `rows + baselines`."
      },
      {
        "type": "paragraph",
        "text": "Use full rows for modular blocks and baseline-only height for captions, folios, and shallow editorial frames."
      }
    ]
  },
  {
    "id": "tooltip-columns-before-reflow",
    "title": "Set columns before reflow",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Choose `cols` before judging paragraph flow."
      },
      {
        "type": "paragraph",
        "text": "A weak line length is usually a measure problem. Reflow and hyphenation work best after the measure is correct."
      }
    ]
  },
  {
    "id": "tooltip-frame-alignment",
    "title": "Align inside the frame",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Alignment positions text inside the configured frame."
      },
      {
        "type": "paragraph",
        "text": "Use it as a compositional decision within a clear frame, not as a repair."
      }
    ]
  },
  {
    "id": "tooltip-custom-type",
    "title": "Use custom type sparingly",
    "blocks": [
      {
        "type": "paragraph",
        "text": "When first selected, `custom` copies the paragraph's resolved size and leading."
      },
      {
        "type": "paragraph",
        "text": "Treat custom type as a local editorial exception after the hierarchy is clear."
      }
    ]
  },
  {
    "id": "tooltip-select-before-nudge",
    "title": "Select before nudging",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Single-click a layer card to select it, then use arrow keys to nudge."
      },
      {
        "type": "paragraph",
        "text": "This keeps positional edits precise and avoids entering edit mode by accident."
      }
    ]
  },
  {
    "id": "tooltip-lock-finished-layers",
    "title": "Lock resolved layers",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Lock layers once their position and role are resolved."
      },
      {
        "type": "paragraph",
        "text": "Locked layers still show rollover guides, but cannot be moved, edited, duplicated, deleted, or retargeted until unlocked."
      }
    ]
  },
  {
    "id": "tooltip-page-cards",
    "title": "Use page rows for document rhythm",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use the `page` header or list icon to return from a layer stack to the page list."
      },
      {
        "type": "paragraph",
        "text": "Page order is part of the design. Treat it with the same discipline as modular field and hierarchy."
      }
    ]
  },
  {
    "id": "tooltip-facing-pages",
    "title": "Use facing pages only for spreads",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use `facing pages` only when two physical pages need one continuous editorial field."
      },
      {
        "type": "paragraph",
        "text": "A facing spread doubles the column field, mirrors inner and outer margins, and affects physical page variables."
      }
    ]
  },
  {
    "id": "tooltip-preview-guides",
    "title": "Toggle guides while judging",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use the header toggles to inspect baselines, margins, modules, typography, and image placeholders."
      },
      {
        "type": "paragraph",
        "text": "Judge the same layout with and without construction lines. The rhythm should remain visible after the guides disappear."
      }
    ]
  },
  {
    "id": "tooltip-rollover-guides",
    "title": "Rollover guides show the frame",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Hover a layer to see its edit access and placement guides."
      },
      {
        "type": "paragraph",
        "text": "Paragraph guides follow the configured `rows + baselines` frame, not only the visible text bounds."
      }
    ]
  },
  {
    "id": "tooltip-documentation-link",
    "title": "Documentation stays external",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use the documentation link for the full reference. Keep the canvas focused on the layout."
      }
    ]
  },
  {
    "id": "tooltip-export-readiness",
    "title": "Export after the system is stable",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Export should confirm a resolved layout, not repair it."
      },
      {
        "type": "paragraph",
        "text": "Check page order, page range, visible guide toggles, rotation, page numbering, and document variables before export."
      }
    ]
  },
  {
    "id": "tooltip-export-format",
    "title": "Choose export by downstream use",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use `JSON` for editable project exchange, `PDF` for faithful vector output, `SVG` for frozen per-page geometry, and `IDML` for InDesign continuation."
      },
      {
        "type": "paragraph",
        "text": "The normal vector path freezes typography as planned geometry for `PDF`, `SVG`, and `IDML`."
      }
    ]
  },
  {
    "id": "tooltip-export-bleed",
    "title": "Shared vector bleed",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Bleed applies to `PDF`, `SVG`, and `IDML` from one shared control."
      },
      {
        "type": "paragraph",
        "text": "It changes the export box and crop marks, not the page layout math."
      }
    ]
  },
  {
    "id": "tooltip-export-visibility",
    "title": "Visible overlays are exported",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Export follows current guide visibility."
      },
      {
        "type": "paragraph",
        "text": "Turn off construction guides before final output unless they are part of the deliverable."
      }
    ]
  },
  {
    "id": "tooltip-export-progress",
    "title": "Export progress",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Progress is informational. Export continues from the committed page plan."
      }
    ]
  },
  {
    "id": "tooltip-fix-loose-page",
    "title": "If the page feels loose",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Return to baseline, margins, and grid rhythm before editing individual paragraphs."
      },
      {
        "type": "paragraph",
        "text": "Loose layouts usually need a clearer field, not more local styling."
      }
    ]
  },
  {
    "id": "tooltip-fix-weak-type",
    "title": "If text feels weak",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Check hierarchy, measure, leading, and baseline alignment before changing tracking."
      },
      {
        "type": "paragraph",
        "text": "Tracking changes paragraph color. It refines texture; it does not replace hierarchy."
      }
    ]
  },
  {
    "id": "tooltip-grid-reduction",
    "title": "If content falls out of bounds",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Grid reductions are blocked when existing layers would fall outside the new field."
      },
      {
        "type": "paragraph",
        "text": "Resolve layer placement first, then reduce rows or columns."
      }
    ]
  },
  {
    "id": "tooltip-faster-editing",
    "title": "If editing feels slow",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use paragraph zoom, keep one editor open, and retarget from paragraph to paragraph."
      },
      {
        "type": "paragraph",
        "text": "The most efficient workflow is staying in context while moving deliberately through the page."
      }
    ]
  }
] as const satisfies readonly LayoutOpenTooltipItem[]
