import test from "node:test"
import assert from "node:assert/strict"
import fs from "node:fs"
import path from "node:path"

const ROOT = process.cwd()

function readText(relPath) {
  return fs.readFileSync(path.join(ROOT, relPath), "utf8")
}

test("svg export is rendered through the shared page export plan", () => {
  const source = readText("lib/svg-vector-export.ts")
  const plannedSource = readText("core/export/planned-page-export-source.ts")
  assert.match(source, /import\s+\{\s*buildPageExportPlan,\s*type\s+PageExportPlan\s*\}\s+from\s+"@\/core\/layout\/page-export-plan"/)
  assert.match(source, /exportPlan\?:\s*PageExportPlan/)
  assert.match(source, /exportPlan:\s*providedExportPlan/)
  assert.match(source, /const\s+exportPlan\s*=\s*providedExportPlan\s*\?\?\s*buildPageExportPlan\(\{/)
  assert.match(source, /showBaselines,\s*showModules,\s*showMargins,\s*showImagePlaceholders,\s*showTypography,/)
  assert.match(plannedSource, /buildPlannedProjectPageExportSources/)
})

test("svg export emits a bleed-capable svg with page clipping, guide groups, placeholders, and outline groups", () => {
  const source = readText("lib/svg-vector-export.ts")
  assert.match(source, /<svg xmlns="http:\/\/www\.w3\.org\/2000\/svg"/)
  assert.match(source, /import\s+\{[\s\S]*?getExportGuideClipRect,[\s\S]*?type\s+ExportBox[\s\S]*?\}\s+from\s+"@\/lib\/export-box"/)
  assert.doesNotMatch(source, /bleedPt\?:\s*number/)
  assert.doesNotMatch(source, /markCanvasPt\?:\s*number/)
  assert.doesNotMatch(source, /cropMarkOffsetPt\?:\s*number/)
  assert.doesNotMatch(source, /cropMarkLengthPt\?:\s*number/)
  assert.match(source, /exportBox:\s*ExportBox/)
  assert.doesNotMatch(source, /buildExportBoxFromPoints/)
  assert.match(source, /const\s+documentWidth\s*=\s*exportBox\.media\.width/)
  assert.match(source, /const\s+viewBoxX\s*=\s*exportBox\.media\.x/)
  assert.match(source, /const\s+pageClipRect\s*=\s*getExportGuideClipRect\(exportBox,\s*true\)\s*\?\?\s*exportBox\.trim/)
  assert.match(source, /viewBox="\$\{formatNumber\(viewBoxX\)\} \$\{formatNumber\(viewBoxY\)\} \$\{formatNumber\(documentWidth\)\} \$\{formatNumber\(documentHeight\)\}"/)
  assert.match(source, /<rect x="\$\{formatNumber\(exportBox\.media\.x\)\}" y="\$\{formatNumber\(exportBox\.media\.y\)\}" width="\$\{formatNumber\(exportBox\.media\.width\)\}" height="\$\{formatNumber\(exportBox\.media\.height\)\}" fill="#ffffff" \/>/)
  assert.match(source, /<rect x="\$\{formatNumber\(pageClipRect\.x\)\}" y="\$\{formatNumber\(pageClipRect\.y\)\}" width="\$\{formatNumber\(pageClipRect\.width\)\}" height="\$\{formatNumber\(pageClipRect\.height\)\}" fill="\$\{formatSvgColor\(exportPlan\.backgroundColor\)\}" \/>/)
  assert.doesNotMatch(source, /bleedOutlineMarkup/)
  assert.doesNotMatch(source, /stroke="#8c8c8c" stroke-width="0\.25" stroke-dasharray="2 2"/)
  assert.match(source, /const\s+cropMarkMarkup\s*=\s*exportBox\.cropMarkLines\.length\s*>\s*0/)
  assert.match(source, /<g id="crop-marks" fill="none" stroke="#141414" stroke-width="0\.35">/)
  assert.match(source, /<defs><clipPath id="\$\{pageClipId\}"><rect x="\$\{formatNumber\(pageClipRect\.x\)\}" y="\$\{formatNumber\(pageClipRect\.y\)\}" width="\$\{formatNumber\(pageClipRect\.width\)\}" height="\$\{formatNumber\(pageClipRect\.height\)\}" \/><\/clipPath><\/defs>/)
  assert.match(source, /guides-\$\{guideGroup\.id\}/)
  assert.match(source, /<rect id="image-\$\{quoteAttr\(key\)\}"/)
  assert.match(source, /<g id="text-\$\{quoteAttr\(key\)\}"/)
  assert.match(source, /data-text-rendering="glyph-outline"/)
  assert.match(source, /<path d="\$\{quoteAttr\(pathData\)\}"/)
})

test("svg export embeds project metadata in a dedicated rdf block", () => {
  const source = readText("lib/svg-vector-export.ts")
  assert.match(source, /function\s+buildSvgMetadataMarkup\(/)
  assert.match(source, /<metadata>/)
  assert.match(source, /<rdf:RDF xmlns:rdf="http:\/\/www\.w3\.org\/1999\/02\/22-rdf-syntax-ns#">/)
  assert.match(source, /<dc:format>image\/svg\+xml<\/dc:format>/)
  assert.match(source, /<dc:title><rdf:Alt><rdf:li xml:lang="x-default">/)
  assert.match(source, /<dc:description><rdf:Alt><rdf:li xml:lang="x-default">/)
  assert.match(source, /<dc:creator><rdf:Seq><rdf:li>/)
  assert.match(source, /<dc:date><rdf:Seq><rdf:li>/)
  assert.match(source, /<xmp:CreatorTool>/)
  assert.match(source, /metadataMarkup/)
})

test("svg export converts positioned graphemes through the shared vector outline resolver", () => {
  const svgSource = readText("lib/svg-vector-export.ts")
  const outlineSource = readText("lib/vector-text-outline.ts")
  assert.match(svgSource, /\(outlineResolver \?\? resolveTextPlanVectorShapes\)\(textPlan\)/)
  assert.match(svgSource, /buildSvgPathDataFromCommands\(shape\.commands\)/)
  assert.match(outlineSource, /import\s+\{\s*loadOutlineFont,[\s\S]*?\}\s+from\s+"@\/core\/layout\/font-outline"/)
  assert.match(outlineSource, /loadOutlineFont\(fontFamily,\s*fontWeight,\s*italic\)/)
  assert.match(outlineSource, /textPlan\.graphemeLines\.length\s*>\s*0/)
  assert.match(outlineSource, /grapheme\.x/)
  assert.match(outlineSource, /grapheme\.y/)
  assert.match(outlineSource, /outlineFont\.getPath\(/)
  assert.match(outlineSource, /kerning:\s*false/)
  assert.match(outlineSource, /hinting:\s*false/)
})

test("vector exports cache exact relative outline paths without touching preview rendering", () => {
  const outlineSource = readText("lib/vector-text-outline.ts")
  const previewSource = readText("gui/preview/hooks/useTypographyRenderer.ts")
  assert.match(outlineSource, /relativeOutlineCommandCache = new Map<string,\s*readonly OpenTypePathCommand\[\]>\(\)/)
  assert.match(outlineSource, /translateOpenTypeCommands\(relativeCommands,\s*fragment\.x,\s*fragment\.y\)/)
  assert.doesNotMatch(previewSource, /createVectorTextOutlineResolver|resolveTextPlanVectorShapes/)
})

test("svg export keeps block and page rotation explicit in svg transforms", () => {
  const source = readText("lib/svg-vector-export.ts")
  assert.match(source, /function\s+renderRotationTransform\(rotation:\s*number,\s*originX:\s*number,\s*originY:\s*number\)/)
  assert.match(source, /const\s+pageRotationTransform\s*=\s*renderRotationTransform\(/)
  assert.match(source, /const\s+rotationTransform\s*=\s*renderRotationTransform\(/)
})

test("svg export keeps a narrow live-text fallback if outline loading fails unexpectedly", () => {
  const svgSource = readText("lib/svg-vector-export.ts")
  const outlineSource = readText("lib/vector-text-outline.ts")
  assert.match(outlineSource, /if\s*\(!outlineFont\)\s*\{[\s\S]*?fallbackTextShapes\.push/)
  assert.match(svgSource, /xml:space="preserve"/)
  assert.match(svgSource, /data-text-rendering="text-fallback"/)
})

test("export actions support pdf, svg, idml, and json formats with format-specific filenames", () => {
  const source = readText("gui/shell/hooks/useExportActions.ts")
  const formatSource = readText("lib/export-format-options.ts")
  assert.match(formatSource, /export\s+type\s+ExportFormat\s*=\s*"pdf"\s*\|\s*"svg"\s*\|\s*"idml"\s*\|\s*"json"/)
  assert.match(formatSource, /EXPORT_FORMAT_OPTIONS/)
  assert.match(formatSource, /EXPORT_FORMATS/)
  assert.match(formatSource, /EXPORT_VECTOR_FORMATS/)
  assert.match(formatSource, /EXPORT_DOWNLOAD_EXTENSION_PATTERN/)
  assert.match(formatSource, /resolveExportBaseName/)
  assert.match(formatSource, /supportsBleed:\s*true/)
  assert.match(formatSource, /resolveExportDownloadExtension/)
  assert.match(source, /runProjectExport/)
  assert.match(source, /const\s+exportVector\s*=\s*useCallback/)
  assert.match(source, /formats:\s*\[format\]/)
  assert.match(source, /filenames:\s*\{\s*\[format\]:\s*filename\s*\}/)
  assert.match(source, /baseName:\s*resolveExportBaseName\(filename\)/)
  assert.match(source, /shouldForceVectorProgress\(format,\s*progress\)/)
  assert.match(source, /progress\.phase\s*===\s*"preparing"\s*\|\|\s*progress\.phase\s*===\s*"packaging"/)
  assert.match(source, /window\.addEventListener\("keydown",\s*onKeyDown,\s*\{\s*capture:\s*true\s*\}\)/)
  assert.match(source, /document\.addEventListener\("keydown",\s*onKeyDown,\s*\{\s*capture:\s*true\s*\}\)/)
  assert.match(source, /window\.addEventListener\("keyup",\s*onKeyDown,\s*\{\s*capture:\s*true\s*\}\)/)
  assert.match(source, /document\.addEventListener\("keyup",\s*onKeyDown,\s*\{\s*capture:\s*true\s*\}\)/)
  assert.match(source, /event\.stopImmediatePropagation\(\)/)
  assert.match(source, /const\s+getDefaultExportFilename\s*=\s*useCallback\(\(format:\s*ExportFormat,\s*selectedPages:\s*number\)/)
  assert.match(source, /resolveExportDownloadExtension\(format,\s*selectedPages\)/)
  assert.match(source, /const\s+currentProjectSnapshot\s*=\s*activeProject/)
  assert.match(source, /parseProjectExportPageSelectionDraft\(exportRangeDraft,\s*projectPageCount\)/)
  assert.match(source, /filterProjectByExportPageNumbers\(activeProject,\s*parsedPageSelection\.pageNumbers\)/)
  assert.doesNotMatch(source, /buildResolvedProjectPageExportSources/)
  assert.match(source, /const\s+exportSelectedPageCount\s*=\s*parsedPageSelection\.pageNumbers\.length/)
  assert.match(source, /if\s*\(exportFormatDraft\s*!==\s*"json"\s*&&\s*exportSelectedPageCount\s*===\s*0\)\s*return/)
  assert.match(source, /if\s*\(exportFormatDraft\s*===\s*"json"\)\s*\{[\s\S]*?saveJSON\(filename,\s*selectedProject,\s*normalizedMetadata\)/)
  assert.doesNotMatch(source, /jsonCompression|compressedJson/)
  assert.match(source, /normalizeExportBleedOptions\(\{[\s\S]*?supportsExportBleed\(exportFormatDraft\)[\s\S]*?widthMm:\s*Number\(bleedWidthMmDraft\)/)
  assert.match(source, /if\s*\(supportsExportBleed\(exportFormatDraft\)\)\s*\{[\s\S]*?await\s+exportVector\(exportFormatDraft,\s*currentProjectSnapshot,\s*parsedPageSelection\.pageNumbers,\s*currentProjectSnapshot\.visibilitySettings,\s*filename,\s*bleed,\s*normalizedMetadata\)/)
  assert.doesNotMatch(source, /exportViewSettings/)
  assert.doesNotMatch(source, /exportPDF/)
  assert.doesNotMatch(source, /exportSVG/)
  assert.doesNotMatch(source, /exportIDML/)
  assert.match(source, /const\s+defaultRange\s*=\s*\{\s*fromPage:\s*1,\s*toPage:\s*projectPageCount\s*\}/)
  assert.match(source, /author:\s*saveAuthorDraft\.trim\(\),/)
  assert.match(source, /createdAt:\s*nextCreatedAt,/)
})

test("multi-page svg export switches to zip packaging with one file per selected page", () => {
  const source = readText("gui/shell/hooks/useExportActions.ts")
  const engineSource = readText("lib/export-engine.ts")
  const pageSetSource = readText("lib/svg-page-set-export.ts")
  const pageSetWorkerSource = readText("workers/svg-page-set.worker.ts")
  const zipWorkerSource = readText("workers/svg-zip.worker.ts")
  assert.match(source, /svgPackaging:\s*format\s*===\s*"svg"\s*\?\s*"zip"\s*:\s*undefined/)
  assert.match(engineSource, /renderSvgPageSetsWithBrowserWorkers/)
  assert.match(engineSource, /zipSvgFilesWithBrowserWorker/)
  assert.match(engineSource, /function runBrowserPageSetWorkers/)
  assert.match(engineSource, /function runSingleBrowserWorker/)
  assert.match(engineSource, /const svgPageSetCache = new Map/)
  assert.match(engineSource, /getStableRequestCacheKey/)
  assert.match(engineSource, /readPageSetCache\(svgPageSetCache/)
  assert.match(engineSource, /writePageSetCache\(svgPageSetCache/)
  assert.match(engineSource, /function cloneSvgExportFiles/)
  assert.match(engineSource, /runBrowserPageSetWorkers<SvgPageSetWorkerRequest,\s*SvgPageSetWorkerResponse,\s*SvgExportFile\[]>/)
  assert.match(engineSource, /runSingleBrowserWorker<SvgZipWorkerRequest,\s*SvgZipWorkerResponse,\s*Uint8Array>/)
  assert.match(pageSetSource, /renderSvgPageSetFiles/)
  assert.match(pageSetWorkerSource, /renderSvgPageSetFiles/)
  assert.match(zipWorkerSource, /zipSync\(zipEntries\)/)
  assert.match(engineSource, /application\/zip/)
  assert.match(pageSetSource, /_page_\$\{String\(pageNumber\)\.padStart\(3,\s*"0"\)\}_/)
})

test("export dialog exposes an explicit pdf-svg-idml-json format switch", () => {
  const source = readText("gui/dialogs/ExportDialog.tsx")
  const hookSource = readText("gui/shell/hooks/useExportActions.ts")
  const workspaceDialogsSource = readText("gui/dialogs/WorkspaceDialogs.tsx")
  assert.match(source, /SectionHeaderRow\s+label=\{t\("ui\.export\.dialog\.input"\)\}/)
  assert.match(source, /SectionHeaderRow\s+label=\{t\("ui\.export\.dialog\.output"\)\}/)
  assert.doesNotMatch(source, /SectionHeaderRow\s+label="Pages"/)
  assert.match(source, /const\s+showPageRangeControls\s*=\s*previewProject\.pages\.length\s*>\s*1/)
  assert.match(source, /\{showPageRangeControls\s*\?\s*\(/)
  assert.match(source, /<Label className=\{centeredRowLabelClassName\}>\{t\("ui\.export\.dialog\.pages"\)\}<\/Label>/)
  assert.match(source, /placeholder=\{t\("ui\.export\.dialog\.pageRangePlaceholder"\)\}/)
  assert.match(source, /onExportRangeCommit/)
  assert.match(source, /EXPORT_FORMATS\.map\(\(format\)/)
  assert.match(source, /EXPORT_FORMAT_OPTIONS\[format\]\.label/)
  assert.match(source, /onExportFormatChange\(format\)/)
  assert.doesNotMatch(source, /onExportRangeStartChange/)
  assert.doesNotMatch(source, /onExportRangeEndChange/)
  assert.match(source, /aria-pressed=\{bleedEnabledDraft\}[\s\S]*?t\("ui\.export\.dialog\.bleed"\)[\s\S]*?<\/Button>/)
  assert.match(source, /t\("ui\.export\.dialog\.bleedWidth"\)/)
  assert.doesNotMatch(source, /millimeters/)
  assert.doesNotMatch(source, /PDF exports RGB vector geometry/)
  assert.doesNotMatch(source, /SVG exports a ZIP with one outlined SVG per selected page\./)
  assert.doesNotMatch(source, /IDML exports outlined geometry, document bleed, slug canvas, and crop marks outside bleed/)
  assert.doesNotMatch(source, /JSON exports the full editable project document/)
  assert.doesNotMatch(source, /GZIP-Compression/)
  assert.match(source, /EXPORT_FORMAT_OPTIONS\[format\]\.label/)
  assert.match(source, /t\("ui\.export\.dialog\.exportIdml"\)|exportIdml/)
  assert.match(source, /t\("ui\.export\.dialog\.saveJson"\)|saveJson/)
  assert.match(source, /Upload className/)
  assert.match(source, /Loader2 className/)
  assert.match(source, /exportProgress\.currentLabel/)
  assert.match(source, /style=\{\{ width:\s*isExporting \? `\$\{totalProgressPercent\}%` : "0%" \}\}/)
  assert.doesNotMatch(source, /exportDiagnostics\.slice\(-4\)/)
  assert.doesNotMatch(hookSource, /exportDiagnostics|formatExportTimingEntries\(result\)/)
  assert.doesNotMatch(workspaceDialogsSource, /exportDiagnostics=\{exportDialog\.diagnostics\}/)
  const engineSource = readText("lib/export-engine.ts")
  assert.match(engineSource, /pdf:\s*initializing document/)
  assert.match(engineSource, /translateMessage\("ui\.export\.status\.renderingPdfPages",\s*\{\s*count:\s*plannedPages\.length\s*\}\)/)
  assert.match(engineSource, /pdf:\s*finalizing bytes/)
  assert.match(engineSource, /const\s+PLANNING_PROGRESS_PAGE_INTERVAL\s*=\s*DEFAULT_EXPORT_PAGE_SET_SIZE/)
  assert.match(engineSource, /function\s+shouldPublishPlanningProgress/)
  assert.match(engineSource, /currentLabel:\s*translateMessage\("ui\.export\.status\.planning",\s*\{\s*completed,\s*total\s*\}\)/)
  assert.match(engineSource, /currentLabel:\s*translateMessage\("ui\.export\.status\.renderingPdf",\s*\{\s*completed,\s*total:\s*plannedPages\.length\s*\}\)/)
  assert.doesNotMatch(engineSource, /currentLabel:\s*page\.name/)
  assert.match(engineSource, /await\s+yieldForBrowserPlanningProgress\(\)/)
  assert.doesNotMatch(source, /Units \/ Paper Size/)
  assert.doesNotMatch(source, /Ratio:/)
})

test("save dialog remains focused on library metadata rather than json filename export", () => {
  const source = readText("gui/dialogs/SaveLibraryDialog.tsx")
  assert.match(source, /t\("ui\.shell\.dialogs\.saveLibrary\.title"\)/)
  assert.match(source, /t\("ui\.common\.projectTitle"\)/)
  assert.match(source, /t\("ui\.common\.subjectOptional"\)/)
  assert.match(source, /t\("ui\.common\.authorOptional"\)/)
  assert.doesNotMatch(source, /Filename/)
})

test("default pdf and svg filenames no longer encode a paper-size override", () => {
  const source = readText("gui/shell/useShellModel.tsx")
  assert.match(source, /const\s+defaultPdfFilename\s*=\s*useMemo\(\s*\(\)\s*=>\s*`\$\{baseFilename\}_grid\.pdf`/)
  assert.match(source, /const\s+defaultSvgFilename\s*=\s*useMemo\(\s*\(\)\s*=>\s*`\$\{baseFilename\}_grid\.svg`/)
  assert.doesNotMatch(source, /baseFilename}_\$\{exportPaperSize\}_grid\.(pdf|svg)/)
})
